### ISSUE TITLE
Should the default page footer contain a licence or privacy notice?

### ISSUE THREAD

**Issue by cofinoa** [cf-convention/cf-convention.github.io#116]
Al site's pages use the default layout with the following footer:
```
<footer>
   <p>
      <a href="http://github.com/esgf">CODE</a> &bull;
      <a href="http://www-pcmdi.llnl.gov/">PCMDI</a> &bull;
      <a href="http://cmip-pcmdi.llnl.gov/cmip5/">CMIP5</a> &bull;
      <a href="http://www.llnl.gov/disclaimer.html">Privacy &amp; Legal Notice</a>
   </p>
 </footer>
```
which references to ESGF or CMIP5, and some links are broken (Privacy and Legal Notice)

**Comment by cofinoa** [comment]
I would suggest to replace by: 

```html
<footer>
      <p>
      <a href="TO BE COMPLETED">Privacy &amp; Legal Notice</a> &bull;
      <a href="TO BE COMPLETED">LICENSE</a> &bull;
      <a href="https://github.com/cf-convention/cf-convention.github.io/issues/new/choose"> Report any issue with this web page<a> &bull;
      <a href="https://commons.wikimedia.org/wiki/File:Simple_Globe.svg"><em>Globe Logo</em></a>
          by <a href="https://commons.wikimedia.org/wiki/User:Tokyoship"> Tokyoship </a> 
          / <a href="https://commons.wikimedia.org">Wikimedia Commons</a> 
          / <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA-3.0</a>
      </p>
</footer>
```

which renders to: 
<footer>
      <p>
      <a href="TO BE COMPLETED">Privacy &amp; Legal Notice</a> &bull;
      <a href="TO BE COMPLETED">LICENSE</a> &bull;
      <a href="https://github.com/cf-convention/cf-convention.github.io/issues/new/choose"> Report any issue with this web page<a> &bull;
      <a href="https://commons.wikimedia.org/wiki/File:Simple_Globe.svg"><em>Globe Logo</em></a>
          by <a href="https://commons.wikimedia.org/wiki/User:Tokyoship"> Tokyoship </a> 
          / <a href="https://commons.wikimedia.org">Wikimedia Commons</a> 
          / <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA-3.0</a>
      </p>
</footer>

I'm not sure which  `privacy legal notice` should be added. The same with `LICENSE`.

**Comment by cofinoa** [comment]
This relates to: #58 #65 #64 #67 (?)

**Comment by erget** [comment]
We also need an "Edit on GitHub!" link - might the footer be a good place for this?

**Comment by ethanrd** [comment]
@erget - I think we want a "Edit on GitHub" kind of link to be very prominent, not something you have to go looking for. The footer seems like a place for things you are required to have or want available if someone is looking for it. Somewhere at the top seems better for things we want everyone to see.

A lot of projects seem to have a "Fork this on GitHub", "Improve this Page", or similar in the top right corner. So, maybe that is a good (standard?) place for it?

**Comment by DocOtak** [comment]
Be careful where a "edit on github" type thing links to, on almost all the built docs I see that use sphinx, that button almost always lands me on a 404 page, it happens enough that I usually search for the gh project myself.

**Comment by erget** [comment]
@ethanrd absolutely right... The easiest way to get a standard GH pages template but there's probably a badge we can embed everywhere. For the sake of not polluting this issue I'm dropping that point - will try not to forget it for the future ;)

**Comment by ethanrd** [comment]
@DocOtak - Yup, I've seen that too. Got to me careful with that.
@erget - Standard GHPages templates also, I think, handle resizing browser windows and mobile screens better than the current CF pages. I'll add two issues: 1) add "Edit this page on GitHub" badge; 2) Move to standard GHPages template.

**Comment by bnlawrence** [comment]
I started writing about this a while ago, and got distracted. Anyway, wrt license/privacy notice, I think we should use a CC license (probably [this one](https://creativecommons.org/share-your-work/public-domain/cc0/)). We're not a legal entity and don't want to be one, so it's not obvious that we need to bother with any attribution of rights *to* us. We might, if we were paranoid, require all pull requests to include something like the following at the bottom of the explanation:

I certify that I wrote this content and/or otherwise have the right to pass it on into this documentation where it will be covered by [insert our cc license]

**Comment by JonathanGregory** [comment]
I have proposed to put a link to the discussion page in the footer in https://github.com/cf-convention/cf-convention.github.io/issues/162, along the line suggested by @erget, and also remove the existing contents of the footer, as originally proposed by @cofinoa in opening this issue. I hope that will be OK for those aspects. Please discuss them in https://github.com/cf-convention/cf-convention.github.io/issues/162 if not.

There remains the issue of whether there should be a licence, perhaps also stated in the footer, which is discussed in this issue. I will change its title to make that more obvious.

**Comment by erget** [comment]
This conversation got a bit diffuse and spawned a bunch of more focused issues that I think are all worthwhile. I think we should refocus on the license/privacy notice issue. Is anyone interested in pursuing this?

**Comment by JonathanGregory** [comment]
Since no further interest was expressed in this issue during the last 14 months, I am closing it now.
