### ISSUE TITLE
The Standard Name page it's part of the Documents page 

### ISSUE THREAD

**Issue by cofinoa** [cf-convention/cf-convention.github.io#118]
The Standard name page it's redundant with the contents of the Documents page.

I don't the purpose of that but IMO it's confusing having both.

**Comment by JonathanGregory** [comment]
Dear @cofinoa 
Yes, I see what you mean: standard names and conventions are treated in different ways. http://cfconventions.org/standard-names.html (all versions of the standard names table) appears as "Standard names" on the bar at the top, but http://cfconventions.org/latest.html (latest version of the conventions document) does not appear on the bar at the top. Both of them are listed below in "Quick links". In the bar at the top we have "Documents", which links http://cfconventions.org/documents.html; that's a different page listing all the versions of both conventions and standard names. This is all rather confusing.
Jonathan

**Comment by JonathanGregory** [comment]
I have raised this concern on https://github.com/cf-convention/cf-convention.github.io/issues/162, where I hope it can be resolved, so I'll close this issue. Thanks, @cofinoa
