### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-convention.github.io#122]
Point of order: I've updated this summary to capture discussion strewn throughout comments below and hidden those comments as I felt relevant. They're still there but they clutter less visually now that they're only shown in minimised form. Unresolved ones are left standing.

@JonathanGregory @davidhassell @ethanrd this is probably of interest to you.

This issue is sharded off of #102. I have moved the relevant commit via cherry-pick and rebased the original PR in order to keep things focused. The goal is to add CONTRIBUTING.md to this repository, which is the source for the CF website. It is implemented by #121.

I've tried to capture the relevant outstanding discussion on the topic of CONTRIBUTING.md from #102 to here. Of course, this is abridged now and I'm adding my own opinions, which is why I've pinged you for transparency. Based on the discussion from https://github.com/cf-convention/cf-convention.github.io/issues/102#issuecomment-641346514 ff. I plan to add the following labels to round out the associated PR:
- [x] Governance: requiring oversight from the governance pannel
- [x] Update/defect: to correct mistakes or update decisions, to be merged by a member of the Committees or Governance Panel as they correct / clarify decisions they've already made
- [x] Enhancement: improving website UX, oversight from IMS team or any Committee or Panel member
- [x] GitHub problem: Correct technical problem with website build, etc.
- [x] Typo: Correct a trivial mistake, oversight from anyone with merge rights

Changes from that proposed by @JonathanGregory (let me know what you think about this please):
- I think we can live without a "duplicate" label and am not proposing to create one
- I'm also proposing foregoing the 3-week rule for the website and instead only requiring oversight of the people listed next to each label so that we're able to modify the website faster if needed. IMO the 3-week rule makes sense for documentation like the Conventions, but the website has the intent of being an index and providing up-to-date information at all times, and in cases like that of the workshop week before last it was essential to be able to make frequent updates without overhead.

The gist of it is:
- CONTRIBUTING.md basically tells a contributor to use the appropriate issue type
- Each issue tells you what approval is necessary for merging when the issue is created
- I have not applied a waiting period to any merges, as I think it is good to be able to change the website rapidly if we need to
- Approvals are required from a single member of the bodies described above per issue type, **with the exception of governance-related issues** - for that, 2 approvals are needed (because this should be done very carefully!)

Note that I also haven't listed the GitHub handles of the members anywhere. I think it might make sense to use automatic assignment to facilitate finding moderators but this is an idea that should be pursued in a separate issue as noted back in #102.

**Comment by erget** [comment]
I've now reduced this to a very tiny PR full of very tiny files. The gist of it is:
- CONTRIBUTING.md basically tells a contributor to use the appropriate issue type
- Each issue tells you what approval is necessary for merging when the issue is created
- I have not applied a waiting period to any merges, as I think it is good to be able to change the website rapidly if we need to
- Approvals are required from a single member of the bodies described above per issue type, **with the exception of governance-related issues** - for that, 2 approvals are needed (because this should be done very carefully!)

Note that I also haven't listed the GitHub handles of the members anywhere. I think it might make sense to use automatic assignment to facilitate finding moderators but this is an idea that should be pursued in a separate issue as noted back in #102.

With these changes I consider the PR ready for review and have removed its draft status. Thoughts?

**Comment by JonathanGregory** [comment]
Dear Daniel

Thanks for this. I agree with your approach. I appreciate that you have a fondness for minimal text, but I'd like to advocate some additions! I agree that text should be as short as possible - but not shorter. Here are my opinions, to add to yours. I think, however, that this whole issue is a governance decision, and so the governance panel must approve the issue and PR (with @ethanrd in the chair :-)

  * It would be useful for `CONTRIBUTING` to state that proposals to change the convention should be made as an issue in the `conventions` repo (not this one), and proposals about standard names or questions (rather than proposals) about any CF matter as issues in the `discuss` repo (not this one).

  * All your small files specify `defect` as the label. Presumably they should all be different.

  * I think "about" should say more for `enhancement`. It's not just look and feel i.e. presentation, but also content to make the website more useful. For example, adding a new FAQ would be an enhancement. The content already exists in principle, but it's being repackaged. Hence I think `enhancements` are more serious, and they do need a waiting period for comments, to allow people to have time to think or to return from holidays, and it might as well be three weeks with no unsatisfied comment, as for conventions enhancements. I think approval by one person is OK (rather than support by three, as for conventions enhancements), provided you add that the proposer cannot give approval.

  * I appreciate that `update`s may have to be quick, like for the meeting. To permit this, I suggest that it's helpful to distinguish them from enhancements, as I did in my proposals for labels. An update is to change the text on the website in a way which reflects decisions already made by the governance panel or the committees. Hence, if the panel or committees have delegated responsibility to organise the meeting to a subcommittee, the subcommittee can decide it's OK to update the website whenever needed about the meeting, and that's a decision "already made". Approval by one qualified person and no delay seems OK.

  * Clarify that a `defect` or `typo` issue in this repo is to correct the *website* (not the convention).

  * For `defect`, `typo` and `GitHubProblem` I agree that approval by one qualified person and no delay is OK.

  * For `governance`, we need more "about". My proposed text was/is: to alter anything of substance concerning the constitution of CF, its committees, the rules for altering the convention, and the ways in which CF is maintained and published (including GitHub and the website). Governance decisions are ones that the governance panel has to make, so we can say that. I now think that we shouldn't state a number of qualifying members or a time-delay for this kind. Instead, we can say just "Issues of this kind will be decided by the governance panel." There aren't any rules about how the governance panel makes decisions, because it's generally informal and done by email, as you know, but there's no reason why it should be slow. We say in the constitution now that the governance panel has to record what and how it decided, and so it evidently makes sense that its decisions and reasons would be recorded in `governance` issues in this repo.

Cheers

Jonathan

**Comment by erget** [comment]
Hi @JonathanGregory thanks for this feedback - as I noted above I considered the PR ready for review, but wasn't proposing we merge it straightaway. I'll address your points inline below.

> ...
> Thanks for this. I agree with your approach. I appreciate that you have a fondness for minimal text, but I'd like to advocate some additions! I agree that text should be as short as possible - but not shorter. Here are my opinions, to add to yours. I think, however, that this whole issue is a governance decision, and so the governance panel must approve the issue and PR (with @ethanrd in the chair :-)

Agreed. Once this is in a state that looks "mostly good" I propose addressing the question to the GP as a whole. Hopefully by that time it's in a state where unanimous agreement is straightforward, but we'll see where the discussion goes.

> * It would be useful for `CONTRIBUTING` to state that proposals to change the convention should be made as an issue in the `conventions` repo (not this one), and proposals about standard names or questions (rather than proposals) about any CF matter as issues in the `discuss` repo (not this one).

Done in d916a8f.

> * All your small files specify `defect` as the label. Presumably they should all be different.

Oops, right you are. Fixed in 61dfb40.

> * I think "about" should say more for `enhancement`. It's not just look and feel i.e. presentation, but also content to make the website more useful. For example, adding a new FAQ would be an enhancement. The content already exists in principle, but it's being repackaged. Hence I think `enhancements` are more serious, and they do need a waiting period for comments, to allow people to have time to think or to return from holidays, and it might as well be three weeks with no unsatisfied comment, as for conventions enhancements. I think approval by one person is OK (rather than support by three, as for conventions enhancements), provided you add that the proposer cannot give approval.

That's fine by me. I've implemented that in e725d06.

> * I appreciate that `update`s may have to be quick, like for the meeting. To permit this, I suggest that it's helpful to distinguish them from enhancements, as I did in my proposals for labels. An update is to change the text on the website in a way which reflects decisions already made by the governance panel or the committees. Hence, if the panel or committees have delegated responsibility to organise the meeting to a subcommittee, the subcommittee can decide it's OK to update the website whenever needed about the meeting, and that's a decision "already made". Approval by one qualified person and no delay seems OK.

See 846e22c for this one. I'd be interested in your thoughts here; I've proposed that if somebody is proposing updates on the behalf of one of the governing bodies you mention, they can also self-approve. This only applies of course for this type of issue.

> * Clarify that a `defect` or `typo` issue in this repo is to correct the _website_ (not the convention).

🤷‍♀️ fine by me, see f4cdc48.

> * For `defect`, `typo` and `GitHubProblem` I agree that approval by one qualified person and no delay is OK.
> * For `governance`, we need more "about". My proposed text was/is: to alter anything of substance concerning the constitution of CF, its committees, the rules for altering the convention, and the ways in which CF is maintained and published (including GitHub and the website). Governance decisions are ones that the governance panel has to make, so we can say that. I now think that we shouldn't state a number of qualifying members or a time-delay for this kind. Instead, we can say just "Issues of this kind will be decided by the governance panel." There aren't any rules about how the governance panel makes decisions, because it's generally informal and done by email, as you know, but there's no reason why it should be slow. We say in the constitution now that the governance panel has to record what and how it decided, and so it evidently makes sense that its decisions and reasons would be recorded in `governance` issues in this repo.

I agree with that. I've modified the formatting of your text proposal. I also modified it in the effort to differentiate between this class of issue and GitHub issues. This is all in deae20b. What do you think?

**Comment by JonathanGregory** [comment]
Thanks, @erget. I'll reply next week. I've run out of time for CF this week!

**Comment by JonathanGregory** [comment]
Dear Daniel @erget

Regarding `update`, I feel that self-approval isn't an effective review. You need a different person to check for mistakes or misunderstandings. I think it would be logical to say

  Updates to the website should reflect decisions that have already been made by the Governance Panel or the Conventions or Standard Names Committees. They must be approved by a member of the Committee which made the decision. They can be merged immediately after approval.

Regarding `enhancement`, I wrote, "they do need a waiting period for comments, to allow people to have time to think or to return from holidays, and it might as well be three weeks with no unsatisfied comment, as for conventions enhancements. I think approval by one person is OK ... provided you add that the proposer cannot give approval." You said this was fine by you, but I don't think you implemented those bits.

Best wishes

Jonathan

**Comment by erget** [comment]
Hi @JonathanGregory , 

Thanks for those comments! I am finally getting back to this issue now. To keep the conversation focused I hid all of the comments that were made above and that had resulted in agreement; I'm keeping [your previous one](https://github.com/cf-convention/cf-convention.github.io/issues/122#issuecomment-657706176) unhidden and responding to it here.

There are 2 outstanding issues as far as I can tell:

# Reviews of updates
> Regarding `update`, I feel that self-approval isn't an effective review. You need a different person to check for mistakes or misunderstandings. I think it would be logical to say
> 
> Updates to the website should reflect decisions that have already been made by the Governance Panel or the Conventions or Standard Names Committees. They must be approved by a member of the Committee which made the decision. They can be merged immediately after approval.

I'm not sure where we disagree here. The text currently reads

> Updates to the website must be approved by a member of the Conventions Committee and Standard Names Committee, the Governance Panel, or someone to whom they have delegated this responsibility.
Updates should reflect decisions that have already been made by the Governance Panel or one of the Committees.
They can be merged immediately after approval.
Furthermore, if they are proposed by someone who has the authority to merge such an update, that person can self-approve the update.

So self-approval is only possible in the case that the person making the update is "a member of the Conventions Committee and Standard Names Committee, the Governance Panel, or someone to whom they have delegated this responsibility" of making the update. This person will have been carefully chosen and the body who delegates the task of making the update will only choose them if they are sure that the person in question will do everything in their power to ensure that the all necessary checks have been done before publishing something.

The reason I have worded things that way is that I believe that this is flexible - i.e. it only allows certain people to make certain changes, as delegation is limited to a specific scope. As an example, the organising committee of the annual workshop might use this authority to make updates within minutes in order to ensure that the workshop runs smoothly. After the workshop is closed out, the authority to make these updates expires. And I don't believe that there is a real danger that people will make updates unilaterally - updates can only be made if they have already been agreed with everybody who needs consulting. Asking somebody else to proofread those updates only adds an additional layer of approval, without generating benefit.

So, in this case, I think we're working with people whom we can trust, and making the process too onerous will only lead to it not being followed. Note that we currently have no CONTRIBUTING.md at all concerning the website and therefore no guidelines to refer to, and nonetheless I'm still discussing this until we reach consensus, rather than making the updates on my own. I believe that we can expect this behaviour from everyone to whom we've granted write access to the repository.

So I've spent all this time arguing a point that we might already be agreed on but I think it's worth it being extra clear here. Do you see this differently?

# Comment period for enhancements
> Regarding `enhancement`, I wrote, "they do need a waiting period for comments, to allow people to have time to think or to return from holidays, and it might as well be three weeks with no unsatisfied comment, as for conventions enhancements. I think approval by one person is OK ... provided you add that the proposer cannot give approval." You said this was fine by you, but I don't think you implemented those bits.

I'm sorry about this! It slipped past me but has now been implemented in 56f06a462483d93911105de730d42733faa69839.

What do you think?

Cheers,
Daniel

**Comment by JonathanGregory** [comment]
Dear Daniel @erget

Thanks for returning to this.

Regarding `enhancement`, I believe we should note that the proposer cannot approve the proposal.

Regarding `update`, I'm not concerned about abuse of the rules. I trust the people who might make updates. My concern is about mistakes. I believe it is a common procedure to seek review from someone else before updating a public document, and I don't see why it should introduce a big delay, since there are plenty of people who could do the review and approve the update. It may even save time overall by preventing mistakes which would have to be rectified. If my view on this point is out of line with the general view, I'll accept the majority decision.

Did we decide to have labels for each of these categories of issue? If so that could be mentioned in CONTRIBUTING. It's useful because it indicates which rules will apply.

Best wishes

Jonathan

**Comment by davidhassell** [comment]
Hi @erget and @JonathanGregory 

Thanks for working on this.

In CONTIBUTING.md there is the line "Details are noted in the relevant issue template." - could you you expand on what this means? Is it just the details of which bodies are required to give approval? If so I don't think this line adds much to the previous few lines. If not, ...

Regarding `update`, I'm not sure that the possibility of a limited scope is that clear in the text, and I think that outside of such special events, I agree that approval should be sought. How about replacing the last line ("Furthermore ...") with "To more easily allow multiple updates relating to a particular topic (such as recording the minutes of the annual meeting), a member of the governance committee may temporarily nominate people to self-approve updates."?

Thanks,
David

**Comment by erget** [comment]
Hi @JonathanGregory, @davidhassell,

Addressing [this](https://github.com/cf-convention/cf-convention.github.io/issues/122#issuecomment-712454385):
> Regarding `enhancement`, I believe we should note that the proposer cannot approve the proposal.

Done in a3af3a1.
 
> Regarding `update`, I'm not concerned about abuse of the rules. I trust the people who might make updates. My concern is about mistakes. I believe it is a common procedure to seek review from someone else before updating a public document, and I don't see why it should introduce a big delay, since there are plenty of people who could do the review and approve the update. It may even save time overall by preventing mistakes which would have to be rectified. If my view on this point is out of line with the general view, I'll accept the majority decision.

I now understand your concern better, and @davidhassell has also proposed some improvements to the wording, so I'll address that below.

> Did we decide to have labels for each of these categories of issue? If so that could be mentioned in CONTRIBUTING. It's useful because it indicates which rules will apply.

Yes, labels are applied automatically depending on the template chosen. I've explained this in 3d92bcd.

Addressing [this](https://github.com/cf-convention/cf-convention.github.io/issues/122#issuecomment-713440039):
> In CONTIBUTING.md there is the line "Details are noted in the relevant issue template." - could you you expand on what this means? Is it just the details of which bodies are required to give approval? If so I don't think this line adds much to the previous few lines. If not, ...

I agree, that is what I meant and I think that 3d92bcd now explains this. I've removed the line in 0e0400f.

> Regarding `update`, I'm not sure that the possibility of a limited scope is that clear in the text, and I think that outside of such special events, I agree that approval should be sought. How about replacing the last line ("Furthermore ...") with "To more easily allow multiple updates relating to a particular topic (such as recording the minutes of the annual meeting), a member of the governance committee may temporarily nominate people to self-approve updates."?

I agree with you both here. What do you think about the text I've proposed in 52180c1?

As always thanks for your input and a pleasant weekend unto all,
Daniel

**Comment by JonathanGregory** [comment]
Dear Daniel @erget 
That looks fine to me now, thanks, except for the unnecessary "both" in "A proposer cannot both approve their own enhancement." Happy weekend
Jonathan

**Comment by erget** [comment]
Hi @JonathanGregory 
Corrected in fc6303d. Good eye.

I propose handling this as an enhancement, i.e. I'm the proposer, and you as a member of the Governance Panel have now approved the proposed enhancement. This means that I'll merge this proposal after 3 weeks on 2020-11-16 barring any objections.

A happy weekend to you as well,
Daniel

**Comment by davidhassell** [comment]
Hi @erget  - looks good to me, thanks.
Happy weekends all round,
David

**Comment by JonathanGregory** [comment]
Yes, that is fine. Thanks.
