### ISSUE TITLE
Replace old content in "Discussion" tab

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/cf-convention.github.io#131]
Hello,

The "Discussion" tab on the web site is very out of date: https://cfconventions.org/discussion.html, as it talks about Trac and the old mailing list, and does not mention GitHub.

I'm happy to suggest a PR to bring this up to date, but thought I'd check first in case anyone who's been looking into these sorts of things was already on to this.

Thanks,
David

**Comment by erget** [comment]
Hi @davidhassell , if anyone was, I probably would have heard of it - thanks for taking the initiative here, I think that's a good idea!

**Comment by JonathanGregory** [comment]
Yes, please do - these things should be brought up to date. Similar points were raised by @jypeter and @taylor13 in issues 58, 65 and 68.

**Comment by davidhassell** [comment]
The proposed new page can viewed in PR #135, or at https://github.com/davidhassell/cf-convention.github.io/blob/discussion/discussion.md

@erget I'm not sure why `Meetings/2020-workshop/process-demo.pdf` got updated in the PR - some sort of git trickery I did by accident, I'm sure. Anyway, I believe the file to be unchanged from master.

**Comment by JonathanGregory** [comment]
Thanks for doing this, David. I have a couple of small comments.

  * Enhancements to the convention. It's not just enhancements, but also defects.

  * Changes to the content of the website. I would say either simply changes to the website, or changes to the content and presentation (or something) of the website.

Best wishes

Jonathan

**Comment by davidhassell** [comment]
Thanks, Jonathan. I have updated PR #135 (https://github.com/davidhassell/cf-convention.github.io/blob/discussion/discussion.md)

**Comment by davidhassell** [comment]
Hello - are there any further comments on this? I tried to refer to the "Discussion" page in a meeting today, was disappointed that it was out of date, and only then remembered that I had proposed a fix for it!

Thanks,
David

**Comment by sadielbartholomew** [comment]
I don't have anything to add except to agree with everyone that it is a great idea to update anything that is out of date. (FYI I went to check the intention on the PR and noticed one small thing so put down a quick review comment too).

**Comment by jypeter** [comment]
Looks good!

**Comment by taylor13** [comment]
I agree.  Looks good.  Thanks.

**Comment by davidhassell** [comment]
Thanks, all (especially @sadielbartholomew for spotting that typo). Much time has passed, and there's plenty of agreement, so I'll get it merged ...
