### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-convention.github.io#132]
# Problem
We have several links on the website that have issues (85 in total):
- 76 point to 404s
- 6 have not-found hosts
- 3 timeout

I propose to fix this.

# Approach
The procedure to fix website defects is as follows:
> Proposals to fix defects must be approved by a member of the Conventions Committee and Standard Names Committee, or the Governance Panel.
They can be merged immediately thereafter.

The [Markup Link Checker](https://github.com/becheran/mlc) (MLC) is available as a GitHub action. I will try integrating that into our pipeline and see if we can't get a report whenever we execute a command. Then I'll fix based on that, pinging people for input as necessary.

@ethanrd I'm a bit confused as to where [the latest conventions document](http://cfconventions.org/cf-conventions/cf-conventions.html) lives. Could you point me in the right place? I think I can have MLC check all HTML and MD files in the repo, so it would hit the Conventions document too (which my scans using [Dr. Link Check](https://www.drlinkcheck.com/) has revealed to have 10 links to 4040s) but I don't find the 1.9 HTML in the repo, unlike everything >1.6.

**Comment by ethanrd** [comment]
@erget - The latest conventions doc gets built on any merge into master (?) and then the .html and .pdf files are pushed to the `gh-pages` branch here (https://github.com/cf-convention/cf-conventions/tree/gh-pages).

**Comment by erget** [comment]
Right. Note to self: When this works, place a check in the Conventions repo to check the Asciidoc.

**Comment by erget** [comment]
Hey folks, there's now an Action that checks for broken links and uploads a report as an issue, alerting us if links are broken. I propose merging that and using it to winnow out broken links over time, as well as to keep the number of bad links down.

This is implemented in #132 and currently checks only the website links. I'm happy to also hook it up for the Conventions doc later on. In the meantime though I'd like to merge this so we can start using it here for cleanup. We can then refine it as we go, e.g. by running it only on errors and adding a "good list" if we know that some links are broken and we want to leave them.

In order to merge this I need a second pair of eyes from @cf-convention/info-mgmt . Anybody else in favour? A good weekend unto all :)

**Comment by sadielbartholomew** [comment]
Hi @erget, I'll try to have a look later today, not to stop anyone else from also going so if they wish, as the more eyes looking over it the better!

**Comment by sadielbartholomew** [comment]
Hi @erget, does #134 still  need reviewing as I can do it (sorry it fell off my radar after my previous comment)?

**Comment by erget** [comment]
Hi @sadielbartholomew no, nobody else has reviewed #134 yet so I'd be happy if you have the time to have a look. Thanks!

**Comment by juhi24** [comment]
On the FAQ page, there is a broken link pointing to http://cfconventions.org/cf-conventions.html#flags

Let me know if reporting broken links here is not useful.

**Comment by erget** [comment]
@juhi24 this is useful, thank you.

@sadielbartholomew have you had a chance to look at #134?

**Comment by sadielbartholomew** [comment]
@erget :laughing: I reviewed it back in March, sorry I assumed you would be notified by GitHub so didn't tag you here. I think I tagged you on my review though, not sure why you wouldn't have seen it?

**Comment by erget** [comment]
@sadielbartholomew 🤦 notification mixup on my side, not yours! Thanks for getting back, I'll process your input and get on with the PR.

**Comment by sadielbartholomew** [comment]
No worries @erget, I imagine you get hundreds of notifcations coming through and I know from experience it is so easy to miss one! I'm glad the review was helpful and you've now got the PR merged :smiley:

**Comment by lkamb** [comment]
Not sure if I should open a new issue or comment here.  Choosing the latter for now.

Three of the links on the https://cfconventions.org/wkt-proj-4.html page are incorrect.  They are the links given for PROJ.4 and EPSG.  They all include an extraneous preamble including the cfconventions.org url as in this example:

https://cfconventions.org/%E2%80%8Bhttp://trac.osgeo.org/proj/

This was checked in both Chrome and Firefox.

I do not see any obvious difference in the page source that would indicate why those 3 links would be mis-processed in this way.

The source page was last edited to fix broken links in #84 

In addition (as was noted elsewhere) the links to the remotesensing.org bring up a wix.com error page saying the domain doesn't exist.

**Comment by JonathanGregory** [comment]
Thanks @lkamb. I am fixing it. Jonathan

**Comment by JonathanGregory** [comment]
Please see https://github.com/cf-convention/cf-convention.github.io/issues/185 and comment there.
