### ISSUE TITLE
CF license, privacy, terms of use - removal of "Privacy & Legal Notice" in the webpage footer

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-convention.github.io#136]
Pursuant [discussion from earlier this year](https://github.com/orgs/cf-convention/teams/gov-panel/discussions/1) I propose removing the "Privacy & Legal Notice" link in the webpage footer. @ethanrd @taylor13 @erget are the ones who chimed in and we had pretty much agreed to take the notice down in the Community Meeting on 2020-06-09.

Would anyone else from the Governance Panel support taking this down this link? If so I would create a pull request and merge it at t+3w from secondment, barring objections.

**Comment by taylor13** [comment]
I still support this. Thanks for following up.

**Comment by JonathanGregory** [comment]
"Anyone else" is me and Bryan, isn't it? Yes, I support it. Thanks. :-)

**Comment by erget** [comment]
Hi @JonathanGregory actually I just meant anybody else from the Governance Panel - although we'd discussed it internally and it seemed we were in agreement, actually making the motion in the repository warrants getting confirmation in my view. Thanks for chiming in, I'll implement the changes hopefully today.

**Comment by erget** [comment]
Done; I'll check back in on 2021-01-04 to merge unless somebody sees an issue!
