### ISSUE TITLE
update to the conventions committee

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#139]
In https://github.com/cf-convention/cf-convention.github.io/pull/138 I have brought the committee membership up to date, and added the dates of expiry of the terms of the current members. As chair of the committee, Karl asked the members who have been on the committee for more than five years already whether they wished to continue. I have assumed that the new five-year terms of those who are continuing began on the day they replied so to Karl. I have moved the names of those who wished to retire to the list of former members, to whom the CF community records their gratitude.

This change implements a decision already made by the governance panel. It can be approved by any member of the governance panel.

**Comment by erget** [comment]
Dear @JonathanGregory , thank you for implementing these changes - I haven't checked the dates of the individual members but am sure that you have, and I approve the PR.

**Comment by JonathanGregory** [comment]
Many thanks.

**Comment by JonathanGregory** [comment]
Does that mean I'm allowed to implement the pull request, @erget? I'm not sure who does that according to rules you've worked out for this repo.

**Comment by erget** [comment]
@JonathanGregory I would class this as an update, which means that it can be merged directly after approval. Since you and I both in the Governance Panel and agree that this is OK, you're free to merge the changes :)

**Comment by JonathanGregory** [comment]
Ooo, what fun!
