### ISSUE TITLE
Correct typos in website

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#150]
Dear @castelao

Thanks for creating https://github.com/cf-convention/cf-convention.github.io/pull/148 and https://github.com/cf-convention/cf-convention.github.io/pull/149. If I correctly understand https://github.com/cf-convention/cf-convention.github.io/blob/master/CONTRIBUTING.md and the "typo" template, an issue is needed to correct a typo in the website. This issue will do! Do you have any comments to make? Probably not, I guess, since these changes are simple.

Best wishes

Jonathan

**Comment by castelao** [comment]
Hi @JonathanGregory , I'm sorry about the missing issue, and thanks for doing that.

A note, the #148 is not really a typo, but an exchange. Daniel is leading the effort on the OG-1.0 and since he will be available, he is a better choice to present that subject at the workshop.

Thanks,

**Comment by JonathanGregory** [comment]
Thanks, @castelao. I will merge your pull requests.
