### ISSUE TITLE
suggestions re Discussion page

### ISSUE THREAD

**Issue by graybeal** [cf-convention/cf-convention.github.io#16]
The DIscussion page (http://cfconventions.org/discussion.html) is good, a few suggestions about its links and their content:
- the About the Trac Site page is good, but includes a lot of information about the email lists, and then says in the last section "Don't send email to the email lists", which really only applies for trac issues. Instead:
  - Mention the Discussion Lists first on the Discussion page, since that is the first thing most people are exposed to
  - Under References on the Discussion page, a page About the Discussion Lists should be first; move Discussion Lists content (from the About the Trac Site link) into that page and reference it from the Trac site
  - The last paragraph in About the Trac Site should say "For Trac issues, don't send email direct..."
- Perhaps organize the links so that the About link comes before the site link(s), and all the LIsts links come before all the Trac links
- Indicate with each link whether it is external to the site (it is disconcerting to try to get more information about something, but be sent directly to the external site instead). This should be a small indication, not sure yet the best way to do it in the Google web sites.

**Comment by JonathanGregory** [comment]
This discussion has been superseded by the migration to GitHub. I have included various relevant changes in https://github.com/cf-convention/cf-convention.github.io/issues/162 so I will close this issue now.
