### ISSUE TITLE
Tidying and improvement of website

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#162]
I propose a number of updates, improvements and corrections to the website, especially the main page `index.html`, as follows. Several of these are the subject of existing dormant issues, as noted below. I feel that it would be good to tidy things up, with the CF meeting coming the week after next.

Although these changes haven't first been discussed, I have proceeded to make a [pull request](https://github.com/cf-convention/cf-convention.github.io/pull/161), because that makes it easier to view the effect of these proposed changes. The affected pages are the main page and the discussion page. See also the [partial mock-up of the modified site](http://www.met.rdg.ac.uk/~jonathan/CF_metadata/210907).

* Remove the very large heading and "Read more" (from `_includes/hero.html`), which is a link to the conventions document, and hence duplicates other more explicitly identifiable links on the page.

* Add a sentence to introduce the standard name table.

* Replace the sentence saying that the conventions "are gaining acceptance", which is bit out of date, with a sentence from Hassell et al (2017) about the applications of CF.

* Add a paragraph to introduce discussion and governance, with a sentence about the community ethos from the constitution.

* Remove the paragraph linking the trac site and email archive (they are kept in the Discussion menu, also proposed by https://github.com/cf-convention/cf-convention.github.io/issues/65).

* Add quick links to the three GitHub issues pages.

* Remove other quick links except those which are directly to documents, because they duplicate the links to menus at the top of the page.

* Put the slides and article from the early days in quick links rather than a paragraph of their own - they're old, but still valid and probably useful.

* Add a quick link to the CF data model paper.

* Correct typo in `_layouts/default.html`.

* Correct labelling of items on the discussion page, minor changes to wording, including more information about the purposes of each forum and GitHub issues.

* Remove Gov Panel Minutes from the navigation bar; the link in the governance page is sufficient.

* Replace the page footer contents (CODE PCMDI CMIP5), which are no longer particularly appropriate (as proposed by https://github.com/cf-convention/cf-convention.github.io/issues/116), with a link to the discussion page, to provide contact info (as requested by https://github.com/cf-convention/cf-convention.github.io/issues/24).

The navigation bar contains both Documents and Standard Names, but standard names are also included in Documents. Thus standard names have two links, but conventions only one. (https://github.com/cf-convention/cf-convention.github.io/issues/118 asks about this). I think we should either remove the Standard Names from the navigation, or remove the standard names from the Documents page and rename it as Conventions.

Update: I have implemented the second of these options, and some other changes:

* Remove standard names from the Documents page and rename it as Conventions in the navigation bar. Change this page from three columns to two (`class="col-md-6"`).
* Replace the text of `latest.html` with links to the Conventions and Standard Name pages, where the latest versions are indicated.
* Add "controlled vocabulary" to the heading of the Standard Names page and mark the current version of the standard name table.
* Change the contact in the footer to point to the Discussion page.
* Put the navigation bar at the top of the page instead of the top of the screen (thanks to @rhattersley).
* Update to release CF-1.9, as @davidhassell  has just prepared to do for the live site.

_Reminder of rules: Enhancement proposals for the website must be approved by a member of the Information Management and Support Team, the Conventions Committee and Standard Names Committee, or the Governance Panel. A proposer cannot approve their own enhancement. After three weeks have elapsed for comments, if no objections are raised, the proposal can be approved and the proposal merged._

**Comment by ethanrd** [comment]
@JonathanGregory - Looks good. Thanks!
I made a few inline comments on the PR.

**Comment by JonathanGregory** [comment]
Thanks, @ethanrd. I have removed the extra "for" in the discussion page and changed the information about trac and email to give the date as you suggested. You also commented

> Since there are multiple libraries and APIs that now support netCDF, perhaps "files created with the NetCDF API" should be changed to "netCDF files" (or "netCDF datasets" to allow for non-file based datasets, e.g., Zarr). Or perhaps "datasets that adhere to the netCDF Data Model"?

That's a good point, but I think it should first be dealt with in the conventions document. The words quoted there come from the introduction to the conventions.

**Comment by JonathanGregory** [comment]
Now I've updated the PR, the links that I had given to the modified versions of the main and discussion pages are out of date. The updated PR has new blobs. Is there a magic way to point to a viewable latest version of a modified file? Also, is there a way to see what the html will look like rendered? I would like to check that the navigation bar and footer are OK, but they don't appear on the Markdown pages. Thanks for advice.

**Comment by davidhassell** [comment]
Thanks @JonathanGregory  - This all looks fine to me. I like Ethan's suggestions, and agree that addressing the netCDF API/dataset/data model issue should be addressed outside of this issue (and that it is a good thing to update address).

**Comment by feggleton** [comment]
These changes look good and will definitely make things clearer on the website!

**Comment by JonathanGregory** [comment]
Thanks for your encouragement, Fran @feggleton, and also your comment by email about the standard name page. Jonathan

**Comment by taylor13** [comment]
I agree with the others.  This looks much better indeed.  Thanks for implementing the changes.

**Comment by JonathanGregory** [comment]
Thanks, Karl @taylor13

**Comment by JonathanGregory** [comment]
I have made further changes as follows:

* Remove standard names from the Documents page and rename it as Conventions in the navigation bar. Change this page from three columns to two (`class="col-md-6"`).
* Replace the text of `latest.html` with links to the Conventions and Standard Name pages, where the latest versions are indicated.
* Add "controlled vocabulary" to the heading of the Standard Names page and mark the current version of the standard name table.
* Change the contact in the footer to point to the Discussion page.
* Put the navigation bar at the top of the page instead of the top of the screen (thanks to @rhattersley).
* Update to release CF-1.9, as @davidhassell  has just prepared to do for the live site.

In order to make it easier what the modified pages looks like, I have created a [partial mock-up of the updated website](http://www.met.rdg.ac.uk/~jonathan/CF_metadata/210907). This comes from downloading the zip file produced by the build of the pull request, as suggested by @rhattersley, and then editing it a bit so that some of the links work. Note that *most links won't work*. :-) This is just to show the layout. In particular, the navigation bar is now fixed to the top of each page, so it goes out of view when you scroll down. Is this OK? I've just noticed that the items in the navigation bar aren't in alphabetical order. I will fix that in the pull request but not in the mock-up.

Jonathan

**Comment by JonathanGregory** [comment]
Does anyone have any further comments on these proposed changes to the CF website (especially the home page)?

I expect that further improvements could be proposed in new issues, but my aim in drafting this set of changes was only to address long-standing problems, several of which were raised in old issues, which I have closed (with comments pointing to this one). If there are no objections, and noting the support which has been expressed, these changes could be accepted in 17 days from now, on 1st Oct.

**Comment by davidhassell** [comment]
Dear Jonathan,

The proposed changes look good me - thanks. (I have spotted a typo on the PR, but that needn't reset the clock.)

David

**Comment by JonathanGregory** [comment]
Thank you, @davidhassell. In https://github.com/cf-convention/cf-convention.github.io/pull/161/commits/93c06117a0458d0f40bc90b3fcbc29a231821ed9 I have repaired the mistake you spotted. I have also updated the mock-up web site (although that link doesn't work!).

**Comment by erget** [comment]
Dear @JonathanGregory in light of the upcoming workshop next week, we'd really like these improvements to be visible before the CF community descends upon it en masse. It would be a benefit for the annual meeting.

Using the grand powers of the Community Meeting Organising Committee, I propose merging these while considering them as meeting preparation. This view is shared by the other members of the organising committee. My apologies for swooping in on your changes but I see that
1. the discussion here has concluded with multiple endorsements and all comments resolved, and
2. the discussions on the corresponding pull request have also been resolved and the merge will be clean
and therefore propose merging your PR.

**Please let me know if you object to this approach in the course of tomorrow,** otherwise I will merge it gratefully on Saturday in preparation of next week's meeting :)

**Comment by taylor13** [comment]
I think that the website "clean up" doesn't need to follow the normal rules for amending the conventions, so the "wait period" can be discarded.  I agree that we are more likely to get further suggestions for improving the website if the ones already suggested (and implemented by Jonathan) are made visible on the official site.
But, I agree that we should wait for Jonathan's o.k. before possibly proceeding.

**Comment by JonathanGregory** [comment]
Dear @erget

I am astonished at your omnipotence, but no-one can resist the spell of such a git magician as yourself. I don't have any more plans or outstanding issues wrt this pull request, so it's fine with me if you merge it provided no-one objects to this accelerated process. Thanks

Jonathan

**Comment by erget** [comment]
Hi all, many thanks for the work that went into these improvements - I have merged the PR, the changes should be visible on the website now.
