### ISSUE TITLE
Latest draft not available

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-convention.github.io#172]
@davidhassell I notice that the latest draft isn't linked on the website - do you know what's up? I can also try to have a look next week, my bet is it has something to do with packaging the newest release.

**Comment by davidhassell** [comment]
Hi @erget - Thanks for spotting this. I've found the typo and fixed it for the draft conventions docs (https://github.com/cf-convention/cf-convention.github.io/commit/8b6bccd3f1ee4718e22e1256a5b800dd3e0ba8c5). The live web site is OK for these, now. The standard names link was also broken, which is also now fixed (https://github.com/cf-convention/cf-convention.github.io/commit/c3c83d2ece14ea909d6325c5f8cdcd0ad1db1b91).

**Comment by davidhassell** [comment]
I've also fixed a couple more links: https://github.com/cf-convention/cf-convention.github.io/commit/338ba40dde7bca787aff34a4c57a8bb855dd6f4d

**Comment by erget** [comment]
One thing i note here is that I at least was warned about broken links by the GitHub Action that checks for them. However, I didn't heed it, because we have too many broken links presently, so such a warning pops out at every PR. This suggests to me that it's important to clean up the links so that we can allow list any that are kept for purely historical reasons; that will prevent such issues moving forward because then any warnings will be real.
