### ISSUE TITLE
Add an "Edit this page on GitHub" badge?

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-convention.github.io#183]
_Originally posted by @ethanrd in https://github.com/cf-convention/cf-convention.github.io/issues/116#issuecomment-641588870 (abridged)_:

> I'll add two issues: 1) add "Edit this page on GitHub" badge; 2) Move to standard GHPages template.

This issue is to add an "Edit this page on GitHub" badge, I'll raise another one for the page template.

**Comment by erget** [comment]
In support:
Makes it really easy to edit pages for contributors (e.g. https://github.com/cf-convention/cf-convention.github.io/issues/116#issuecomment-641552986)

Reasons against:
Potentially people would submit PRs without issues, bypassing processes (https://github.com/cf-convention/cf-convention.github.io/issues/176#issuecomment-924033387)

This was implemented in https://github.com/cf-convention/cf-convention.github.io/commit/f1f94b883e3ff180be80761db3c9713eae329186 with a couple of other updates. I have asked @cofinoa to revert the specific change to the footer until we can decide (hopefully quickly) how to approach this via consensus. If we do decide to keep a link (even if it's presented differently on the page) we can steal the code off of that commit, since it's handy.

I'd be interested in hearing thoughts on this. I personally am in support of having such a link or banner on each page, because it makes it easier to prepare a PR, which can then be associated to an issue.

**Comment by davidhassell** [comment]
Hi @erget, [you wrote](https://github.com/cf-convention/cf-convention.github.io/issues/183#issuecomment-924209309) "[...] such a link or banner on each page, [...] makes it easier to prepare a PR [...]". I was wondering what the endpoint of  "Edit this page on GitHub" would be - is it https://github.com/cf-convention/cf-conventions?

**Comment by erget** [comment]
@JonathanGregory @davidhassell the issue is that in order to edit the webpage currently, you have to understand how it's built and deployed, or at least be able to guess. This happens to be (fairly) straightforward in our case - a tree of Markdown documents with corresponding HTML documents. However, that's not necessarily the case. Having such a link takes you from the HTML page to the corresponding Markdown page directly.

@davidhassell you can check it while we're waiting for @cofinoa to revert the changes - it's a link that is specific to each page. In Markdown that's described [here](https://github.com/cf-convention/cf-convention.github.io/blob/master/_layouts/default.html#L70):
```html
<a href="{{ site.github.repository_url }}/edit/master/{{ page.path }}">Edit this page on GitHub!</a>
```

So that e.g. for the main page that resolves to https://github.com/cf-convention/cf-convention.github.io/edit/master/index.md and for other pages it resolves to the corresponding page, rather than requiring people to go to the repository and then find the right page.

My suggestion is to try it out while the functionality's still there - I expect it'll disappear quickly, since I'll merge it as soon as Antonio proposes the revert - and you can see how handy it is to have such a link.

**Comment by JonathanGregory** [comment]
Dear Daniel @erget

I agree that it's clever and a convenient way to get to the source, and thanks for pointing it out, but doesn't it tacitly encourage anyone to think the right procedure is to edit the page and submit a PR, if they're not familiar with our rules? Especially if this is exactly what they're used to doing in other GitHub organisations. If the main convenience of it is being told where to find the source of the web pages, we could provide that information on the Discussion page. As you say, the mapping is pretty easy for the markdown pages.

By the way, I think it would be helpful to add a statement in README of the website repo directing visitors to the Discussion page and the website issues page if they want to suggest a change to the website. The README of the conventions repo has a notice like that.

Best wishes

Jonathan

**Comment by davidhassell** [comment]
Thanks, Daniel, that's very useful know. I'm currently torn between the various compelling arguments.

If we added we add a PR template that that contains something like:

Fixes: #???
- [ ]  Issue created for discussing these changes

Would that help instruct the casual editor?

**Comment by erget** [comment]
Hi @davidhassell , I don't know if that would work in our situation. In order to find out I just did a test by clicking the button, creating a bogus commit, and then submitting a merge request straight off of that. The PR text was pre-populated with my commit text.

Do you think that this is a potential danger for CF? I see the following potential worries but don't actually see an impact on us due to the safeguards we already have in place

| Potential misunderstanding of process | Worst outcome that could occur due to misuse |
| --- | --- |
| User wants to commit directly to `main` | This would be unusual since all projects automatically have write safeguards. That includes us. Therefore the user would have no option but to open a branch and corresponding PR
| User submits PR without being aware of our processes | One of the repo maintainers sees the PR and advises the user of our change processes, pointing them toward their description and requesting that the open an issue that references the PR. 

This is also taking into consideration the fact that we don't generally have a high edit volume on this repository.

Note also that this applies *only* to editing the webpage, not the Conventions or Conformance documents!

**Comment by JonathanGregory** [comment]
Dear Daniel @erget

Is this much more convenient than navigating to the repo and editing there? - that is possible, isn't it? Going via that route, you would see the README of the repo, which should advise on the procedure.

Perhaps "Edit this page" could invoke a program which would produce a page that explained the procedure, and gave a link for opening a new issue, and another link for actually editing the page. That would work if that GitHub magic markdown could be used to generate an argument to the program. Perhaps such a thing can be done in javascript, which is a language I don't know but no doubt many among us do! (I could do it in php. :smile: )

Jonathan

**Comment by larsbarring** [comment]
This is really way out of my expertise, but could the "Edit this page" be associated with a mouseover/hover over text say displaying something like "You may suggest changes, but please note that there has to be an associated issue explaining the changes"

**Comment by sadielbartholomew** [comment]
> Could somebody check and approve if you're happy?

Hi @erget, great stuff, I've assigned myself and will get it reviewed (but not merge it even if I approve immediately).

**Comment by erget** [comment]
Thanks @sadielbartholomew ! I will merge this on 2021-11-24.
