### ISSUE TITLE
Updates to Information Management and Support Team

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#188]
Following agreement of the governance panel, I have prepared a [pull request](https://github.com/cf-convention/cf-convention.github.io/pull/187) which makes changes to the Governance page, namely

* Add "Team" to "Information Management and Support" and "Former" headings
* Move Jeff Painter and Tanya Reshel to the "Former ..." list
* Add Kyle Halliday and Velimir Mlaker to the "Former ..." list

On behalf of the CF community, the governance panel thanks all four of them for their work in maintaining and improving the CF website and documents.

Jonathan

**Comment by erget** [comment]
FYI - I've linked the PR in the right bar of this issue with the issue itself. Actually I did it from the PR, it works either way. The impact of this is that merging the PR will automatically close this issue.
