### ISSUE TITLE
investigate whether links in repo can work

### ISSUE THREAD

**Issue by graybeal** [cf-convention/cf-convention.github.io#19]
When looking at the content of .md pages in https://github.com/cf-convention/cf-convention.github.io, most links don't work (though they work fine on the actual site). This is perhaps unavoidable, but it makes it hard to maintain the site and check for broken links while editing the pages.

So this task is to see whether there is a way to manage the links so that they are internally consistent in the repository, as well as in the web site itself. (Maybe involving localizing them?)

This task is meant for John G, as a training exercise. But feel free to add comments/suggestions/wisdom.

**Comment by erget** [comment]
This looks stale - I'm closing it but please re-open if relevant!
