### ISSUE TITLE
Difficulty finding lists of "area types" and "standardized regions".

### ISSUE THREAD

**Issue by taylor13** [cf-convention/cf-convention.github.io#191]
I really had to scour the website to find these lists of controlled vocabulary.  For area_type, there seems to be no reference to the lists in the conventions themselves.  We could add links to these lists from some of the following pages:

- https://cfconventions.org/index.html under "quick links"
- the CF conventions document (notably, the area_type list should probably be linked to from section 7.3.3; there is already a link to standardized region in the conventions document)
- the standard names search page

**Comment by davidhassell** [comment]
As did I, eventually finding them under the "Standard Names" tab. I agree with your suggestions, Karl, and might add add that we could add the _latest_ area types and regions under the to the "Conventions" tab.

**Comment by taylor13** [comment]
Yes, and I think the more generic name "vocabularies" is the correct label, but some users might then have more trouble finding the standard names, which they might have heard of and not realize that they are an instance of a vocabulary.    Anyone else have an opinion?   Perhaps I underestimate the users.

**Comment by JonathanGregory** [comment]
Dear Karl @taylor13 

You've just mentioned this issue again, I see. We could make the changes suggested above (last year). I would propose:

* Rename the Standard Name page (which appears in the menu bar at the top) as Vocabularies, which is really what that page covers i.e. all controlled vocabulary, not just standard names.
* Change the line which links the current version of the standard name table under __Quick links__ on the [home page](http://cfconventions.org/) to read "Current versions of CF vocabularies: standard name table, area type table, standardized region list", with each of these three being a link to the latest version.
* Put a link on the [Conventions page](http://cfconventions.org/conventions.html) to the [Vocbularies/Standard Name page](http://cfconventions.org/standard-names.html), saying that it includes `area type`s and `region`s.

You thought it might not be clear that "Vocabularies" means `standard_name`s, `region`s and `area_type`s. If someone comes to the home page looking for these things, however, they will still find them in the __Quick links__. The value of the menu bar is more as shortcuts from other pages, I would say.

Cheers

Jonathan

**Comment by taylor13** [comment]
I think @JonathanGregory has nicely addressed the problem by suggesting specific changes, which I support.  Thanks!

**Comment by davidhassell** [comment]
I also support these changes. I often use the "standard name table" link on the same line as the "Latest release" and "Working draft" links, which perhaps retains the standard name visibility to those who don't think in terms of vocabularies.

**Comment by JonathanGregory** [comment]
I suggest putting the area types and regions in the same line as the one David refers to:

> **Latest release** (1.10) HTML PDF  •  **Working draft** HTML PDF  •  **Standard name table**

and removing the first two **Quick links** 

>  • Latest release of CF conventions
>  • Current version of CF standard name table

because we have the "even quicker" links above, as well as the menus on the navigation bar. Would that be all right?

**Comment by davidhassell** [comment]
That's good for me, @JonathanGregory

**Comment by taylor13** [comment]
Yes; would be an improvement.  Thanks.

**Comment by JonathanGregory** [comment]
I have created [PR #253](https://github.com/cf-convention/cf-convention.github.io/pull/253) to implement this change, which produces a [modified home page](https://github.com/cf-convention/cf-convention.github.io/blob/ac1d4f9410f58401b685b148f2293a48e9bbef32/index.md) and renames the Standard Name page as Vocabulary. This should appear in the navigation bar automatically.

**Comment by JonathanGregory** [comment]
I have changed _Vocabulary_ to _Vocabularies_ in the [PR](https://github.com/cf-convention/cf-convention.github.io/pull/253), as suggested by @davidhassell (in his comment on the PR).

**Comment by JonathanGregory** [comment]
If there are no further comments, and presuming Karl @taylor13 and @davidhassell support the change as currently formulated, this change can be made in another 19 days on 28th September.

**Comment by japamment** [comment]
I support these changes as implemented in the [PR](https://github.com/cf-convention/cf-convention.github.io/pull/253).

**Comment by JonathanGregory** [comment]
Thanks for checking, Alison @japamment

**Comment by davidhassell** [comment]
I do indeed support the change as implemented. Thanks, Jonathan

**Comment by taylor13** [comment]
me too..  thanks, Karl.

**Comment by JonathanGregory** [comment]
No further comments have been made so this change can be made today. Please could someone merge [PR 253](https://github.com/cf-convention/cf-convention.github.io/pull/253) and close this issue? Thanks.

**Comment by JonathanGregory** [comment]
I did it myself in order to cross it off my to-do list! :heavy_check_mark:  I reckoned this was OK since others had reviewed the PR.

**Comment by taylor13** [comment]
Thanks, Jonathan.
