### ISSUE TITLE
broken links on website (cf-conventions-1.8, 1.9)

### ISSUE THREAD

**Issue by LHartten** [cf-convention/cf-convention.github.io#204]
Some if not all links to the NUG Appendix A, Attribute Conventions (http://www.unidata.ucar.edu/software/netcdf/docs/attribute_conventions.html) and the NUG Appendix B, File Format Specifications (http://www.unidata.ucar.edu/software/netcdf/docs/file_format_specifications.html#classic_format_spec) are broken, and go to a 404 Not Found page.

I found the trouble at
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#missing-data
and
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#attribute-appendix
but didn't do an exhaustive search for examples

[Edit: I just realized that in my hurry to answer someone's question I was looking at the previous release.  The problem persists in cf-conventions-1.9]

Cheers,
  Leslie

**Comment by erget** [comment]
Nice find @LHartten ! Would you be interested in submitting a pull request that corrects the links?

**Comment by JonathanGregory** [comment]
These links have been fixed in the [new release](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html). Thanks to the person who fixed them!
