### ISSUE TITLE
Broken link to "Edit this page on GitHub!!" on http://cfconventions.org/discussion.html

### ISSUE THREAD

**Issue by atmodatcode** [cf-convention/cf-convention.github.io#206]
Hello, 
at the bottom of the page
http://cfconventions.org/discussion.html
there is the line
"Edit this page on GitHub!"
which should hold a link directing to this CF Conventions GitHub, 
The actual link is directing to https://github.com/cf-convention/cf-convention.github.io/edit/master/discussion.md
which results in a "Page not found error".
Thanks and regards.

**Comment by erget** [comment]
This should be fixed by #207. Could somebody give a quick review? @castelao ?

**Comment by davidhassell** [comment]
Hi - Will this "break" people's forks? I'm totally for the change, but if it requires a bit of maintenance from folk, then it'd be a good idea to advertise it (after merging) over at https://github.com/cf-convention/discuss

**Comment by erget** [comment]
No, forks are based on repos, not branches, so nothing will break. All the PR does is redirect people to propose changes against `main` rather than against `master`, which was the old default branch which we have now abolished in favour of `main`.

**Comment by JonathanGregory** [comment]
This has been fixed now so I'm closing the issue.
