### ISSUE TITLE
not-used and "not-nicely-named" references on index page

### ISSUE THREAD

**Issue by neumannd** [cf-convention/cf-convention.github.io#214]
There are a few reference links in the end of [index.md](https://github.com/cf-convention/cf-convention.github.io/blob/main/index.md) which are not used in the text. One reference is not intuitively named. In two situations the Link-URLs are in the text whereas should be as references in the end of [index.md](https://github.com/cf-convention/cf-convention.github.io/blob/main/index.md).

**Comment by erget** [comment]
Clear improvement fixing defects, thanks for this :)
