### ISSUE TITLE
create a web page listing contributors to the CF conventions

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#227]
In [issue 359 of conventions](https://github.com/cf-convention/cf-conventions/issues/359), which I have just closed, it was proposed that the secretary of the conventions committee and the chair of the committee (currently @davidhassell and me) should compile a web page containing a list of contributors to conventions discussions, to be updated at least annually, including everyone who has made a non-trivial contribution to any successfully concluded conventions issue, in order to acknowledge their helpful participation.

Those who proposed issues which lead to an enhancement are already acknowledged by being added to the list of authors of the conventions document. We also already have a [web page listing contributors to standard names](http://cfconventions.org/Data/cf-standard-names/docs/standard-name-contributors.html). The proposed new web page would fill a gap in recording the gratitude of the climate research community to those who develop the CF conventions.

No-one objected to the proposal and some support was expressed. I am opening this as a new issue in this repo, where it belongs, to invite any comments or objections. Meanwhile, presuming it will be accepted, we will start to compile a list.

This change to add a page with the initial list agreed by the governance panel is implemented by [pull request 229](https://github.com/cf-convention/cf-convention.github.io/pull/229).

**Comment by erget** [comment]
@JonathanGregory I continue to find this to be a good idea! Thank you for following this up.

**Comment by ethanrd** [comment]
I agree, I think this is a good idea.

**Comment by davidhassell** [comment]
I also agree that this is a good idea.

Instead of updating it annually, perhaps we could add an action for the merging committee member to consider updating the list when the change is accepted?

**Comment by JonathanGregory** [comment]
Dear all

Below is a draft list of contributors to the CF conventions. I compiled this list by looking through all the GitHub conventions issues, Trac tickets and the CF email archive, to identify individuals who had proposed or contributed to the development of an enhancement to the convention or the correction of a defect, or in discussions about possible enhancements which finally concluded in no change being made. I have tried to be comprehensive and fair in putting this list together, with the aim of acknowledging everyone who has made substantial input to the refinement of the conventions. Of course there are many more people who have participated in the discussions in other ways, especially by asking or answering questions. They are part of the CF community as well. 

The affiliations in this list are the most recent ones with which the individuals participated. Some of them have moved since they last participated. There are a couple whose affiliation I couldn't discover; please tell me if you know. Also please tell me of any errors or people who have been omitted.

Happy weekend

Jonathan

```
Ryan Abernathey, Columbia University
Dave Allured, NOAA
Sean Arms, SpectraLogic
Balaji, NOAA and Princeton University
Chris Barker, NOAA
Andrew Barna, SIO/UCSD
Lars Bärring, SMHI
Phil Bentley, UK Met Office
Jim Biard, NOAA
Leon Bilton, ANU
David Blodgett, USGS
Jon Blower, University of Reading
Benno Blumenthal, Columbia University
Philip Cameron-Smith, LLNL
John Caron, Unidata
Antonio Cofiño, University of Cantabria
Lorenzo Corgnati, CNR-ISMAR
Ethan Davis, Unidata
Cecelia DeLuca, NOAA
Martin Desruisseaux, Geomatys
Francisco Doblas-Reyes, ECMWF
Bob Drach, PCMDI, LLNL
Alan D. Snow, Corteva Agriscience
Brian Eaton, NCAR
Steve Emmerson, Unidata
Nan Galbraith, WHOI
Lucile Gaultier, OceanDataLab
Beate Geyer, GKSS
Øystein Godøy, NMI
John Graybeal, Stanford University
Jonathan Gregory, University of Reading and UK Met Office
Tom Gross, NOAA
Steve Hankin, PMEL, NOAA
David Hassell, NCAS and University of Reading
Rosalyn Hatcher, NCAS and University of Reading
Richard Hattersley, UK Met Office
Mark Hedley, UK Met Office
Dan Hollis, UK Met Office
Sylvain Herlédan, OceanDataLab
Heinke Höck, DKRZ
Randy Horne, Excalibur Laboratories Inc
Bert Jagers, Deltares
Aleksandar Jelenak, HDF Group
Martin Juckes, NCAS
Tobias Kölling, MPIM
Dalton Kell, AER
Jamie Kettleborough, UK Met Office
Heiko Klein, NMI
Peter Kuma, Stockholm University
Thomas Lavergne, NMI
Bryan Lawrence, NCAS and University of Reading
Roy Lowry, BODC
Daniel Lee, EUMETSAT
Joao Macedo
Seth McGinnis, NCAR
Don Murray, Unidata
Daniel Neumann, DKRZ
Alison Pamment, CEDA
Patrick Peglar, UK Met Office
Alex Pletzer, Tech-X Corporation
Greg Rappa, MIT
Martin Raspaud, SMHI
Russ Rew, Unidata
Martin Schultz, Jülich Supercomputing Centre
Rich Signell, USGS
Bob Simons, NOAA
Maarten Sneep, KNMI
Anders Meier Soerensen, EUMETSAT
Karl Taylor, PCMDI, LLNL
Etienne Tourigny
Micah Wengren, NOAA
Timothy Whiteaker, University of Texas
John Wilkin, Rutgers University
Charlie Zender, University of California, Irvine
Klaus Zimmermann, SMHI
```

**Comment by JonathanGregory** [comment]
I have created https://github.com/cf-convention/cf-convention.github.io/pull/229 to implement this change

**Comment by taylor13** [comment]
I support this proposal.  One approach to keeping it up-to-date would be to follow a variant of David's suggestion: whoever merges an update to the conventions would nominate additions based on those who contributed to the discussion.  These nominations would then be considered once each year by the chair and secretary of the conventions committee who would update the list appropriately.  This would leave out anyone, however, who had contributed to a discussion that reached a dead end.  Some of these people probably deserve credit for the thought and time they spent *attempting* to improve the convention.  Perhaps these could be handled specially.

**Comment by ethanrd** [comment]
Couldn't updating the contributors list be added as a sub-task of the "Authors updated" task in the PR checklist? It seems related and I'm not seeing a strong need for a separate process. For issues that do not result in a change to the conventions document, it could be up to the moderator on whether to make a PR for adding to the contributors list.

Whatever the process, the `CONTRIBUTING.md` file probably should have some text added about the contributors list.

**Comment by ethanrd** [comment]
Oh right. The contributor list is in a different repo. So my suggestion above needs a bit of tweaking. But I think the general idea could still work.

**Comment by erget** [comment]
@ethanrd I think that works as long as the onus is on the moderator, which IMO is not unreasonable. Thoughts?

**Comment by JonathanGregory** [comment]
Dear all

The governance panel has approved the page listing contributors. Therefore that can be implemented straight away as an agreed update. Please could somehow else check and merge the PR? Thanks.

This issue can remain open for the discussion of how to update the list in future, as in the last few contributions.

Cheers

Jonathan

**Comment by JonathanGregory** [comment]
I have just modified https://github.com/cf-convention/cf-convention.github.io/pull/229 to add Guilherme Castelão, SIO/UCSD, whom I had accidentally omitted. Sorry about that. Jonathan

**Comment by erget** [comment]
Hi @JonathanGregory I've merged this as agreed, but I'd prefer not to leave this issue open indefinitely - seems like a good way for it to get orphaned. The wider question is how we keep the list up-to-date, and for that I think we need to update either the contribution guidelines or the release procedures. Open to discussion on that front and will open a separate issue.
