### ISSUE TITLE
remaining documents to copy

### ISSUE THREAD

**Issue by graybeal** [cf-convention/cf-convention.github.io#23]
I wasn't sure if it was intentional, but a significant number of documents from the old site haven't made it to the new site (that I can tell).  Below are the links from old location to the new location I think they should go.

here I'm following the principle that we shouldn't lose anything from the old site, but maybe decisions have been made to let some things go. If so we can document those decisions in a page on the new site.

| Old | New | Comments |
| --- | --- | --- |
| http://helene.llnl.gov/cf/documents/cf-standard-names/about | http://cfconventions.org/standard-names.html | insert as text at the top of the page |
| http://helene.llnl.gov/cf/documents/cf-standard-names/ecmwf-grib-mapping | http://cfconventions.org/standard-names.html | as 1st of 3 in list under new 'Mappings' section |
| http://helene.llnl.gov/cf/documents/cf-standard-names/ncep-grib-code-cf-standard-name-mapping | http://cfconventions.org/standard-names.html | as 2nd of 3 in list under new 'Mappings' section |
| http://helene.llnl.gov/cf/documents/cf-standard-names/pcmdi-name-cf-standard-name-mapping | http://cfconventions.org/standard-names.html | as 3rd of 3 in list under new 'Mappings' section |
| http://helene.llnl.gov/cf/documents/cf-standard-names/area-type-table/1 | http://cfconventions.org/documents.html | Within area type table section (just like e.g., names) |
| http://helene.llnl.gov/cf/documents | http://cfconventions.org/documents.html | All standards documents should be kept, yes? |
| http://helene.llnl.gov/cf/documents | various places | All docs in right column should be kept too |

**Comment by rhattersley** [comment]
The NCEP & PCMDI standard name mappings still seem to be absent, and no longer available at their old location. Is there some other URL where they are hosted?

**Comment by rhattersley** [comment]
> The NCEP & PCMDI standard name mappings still seem to be absent

The same goes for the ECMWF GRIB mapping - sorry for not mentioning that previously.

**Comment by mattben** [comment]
I was able to recover the old site, and the links above are no longer broken. Are these pages still needed? if so I will do it today. Also where is this ECMWF GRIB mapping file?

**Comment by rhattersley** [comment]
> Are these pages still needed?

Ideally, yes - the CF conventions document contains (currently broken) links to those pages. The easiest and least controversial change to the conventions would be to update the URLs to point to their new location.

**Comment by japamment** [comment]
@mattben do we have a copy of the list of standard name contributors that used to be linked from the Standard Names page on the old web site? If so, please could it be added to the repo and linked from the new Standard Names top level page?

**Comment by erget** [comment]
This look relevant, also in the course of getting our link checking up to snuff. Anybody interested in picking up the torch?

**Comment by JonathanGregory** [comment]
I believe all those documents were rescued, including the list of standard name contribtutors, except for the tables of equivalences to GRIB and PCMDI. That information is included in the standard name table itself, although it is not maintained as far as I know, but that's a separate issue. I think this one could be closed, unless anyone knows otherwise.
