### ISSUE TITLE
Mechanism to keep contributors list up to date

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-convention.github.io#230]
We need to keep the contributors list up to date. Some ideas floating around have been
- update `CONTRIBUTING.md` to have authors or moderators open a new PR for the website when closing a discussion
- add a step to the release procedures where we review PRs and update the list

Might be a better way to do this that's not encompassed in what's above.

People who've already expressed interest: @JonathanGregory @davidhassell @ethanrd @taylor13

> Hi @JonathanGregory I've merged this as agreed, but I'd prefer not to leave this issue open indefinitely - seems like a good way for it to get orphaned. The wider question is how we keep the list up-to-date, and for that I think we need to update either the contribution guidelines or the release procedures. Open to discussion on that front and will open a separate issue.

_Originally posted by @erget in https://github.com/cf-convention/cf-convention.github.io/issues/227#issuecomment-1212828767_

**Comment by JonathanGregory** [comment]
Thanks for merging the update and for opening this issue, Daniel @erget.

In order to make it a bit easier for moderators, perhaps we could ask them in `CONTRIBUTING.md` to _email_ the chair and secretary of the conventions committee with the names of participants who contributed substantially. That would be easier than opening a PR. Then it would be the responsibility of those officers to compile a list for use in updating the web page annually as part of the release procedure. I think it's necessary to have some moderation to make sure we're consistent in the approach, and also to include names from any discussions which concluded without agreement, as Karl @taylor13 reminded us.

Happy Friday

Jonathan

**Comment by erget** [comment]
Hi @JonathanGregory , I'm not opposed to the approach in general, but would prefer to keep the communications on GitHub rather than via email to the 2 officers. What do you think of asking the moderator to _tag_ them when a discussion concludes? In that case both would get an email (unless they've turned off those types of notifications) and the discussion would all take place on the same platform.

**Comment by JonathanGregory** [comment]
Perhaps even simpler than that would be for the moderator to mention significant contributors to the successful conclusion of the discussion when they wind up the issue.

**Comment by erget** [comment]
True... Under the assumption that that gets caught by another process that sweeps up the concluded issues. Could be a period review of all the closed issues, for example, but something would need to happen to pick up the mentions.

**Comment by JonathanGregory** [comment]
Yes, that's right, but I think we have to sweep the issues anyway in order to catch the ones which were closed inconclusively.

**Comment by erget** [comment]
Ok. So that means we'd need 2 updates, both in the Conventions repo:

1. `CONTRIBUTING.md` gets updated to request that moderators propose users who've contributed substantially to the discussion at hand (and aren't already in the contributors list) when concluding discussions
2. The as-yet hypothetical [RELEASE.md](https://github.com/cf-convention/cf-conventions/issues/371) includes a check of the issues that have been closed since the last release to find contributors to add to the website repo

Correct?

**Comment by JonathanGregory** [comment]
Yes, that looks right to me. I think it would work. Thanks.

**Comment by erget** [comment]
Please check the PR associated with this issue - I think that solves it, but needs to be merged along with the procedural update referenced in the commit.

**Comment by taylor13** [comment]
Just to register my support for the proposed approach negotiated between @erget and @JonathanGregory .

**Comment by JonathanGregory** [comment]
That looks fine. Thanks very much, @erget. J

**Comment by davidhassell** [comment]
I'm also happy with the solution on the table - thanks, all.

**Comment by erget** [comment]
Ok, I'm closing this issue then because the changes are all in https://github.com/cf-convention/cf-conventions/pull/372; I'll note they've been agreed in that discussion.

**Comment by ethanrd** [comment]
Sorry I missed this discussion. I was out for a long weekend.

I still prefer the option of having moderators create a PR to capture the additions to the contributor list. It seems less prone to error or missing an addition altogether. And, while an additional step, it is a pretty straight forward step that can easily be done through the GitHub web interface, through the [edit page for the contributor list file](https://github.com/cf-convention/cf-convention.github.io/edit/main/conventions_contributors.md).

On the other hand, I'm don't feel that strongly about it. So, I'm good with the above agreed plan.

**Comment by taylor13** [comment]
Sad to say, I have not yet learned how to create a PR.  There might be other fuddy duddy potential moderators in the same boat, who might decline to moderate a discussion to avoid having to learn how to create a PR.  So thanks for not feeling "strongly about it".
