### ISSUE TITLE
cfconventions.org needs contact info

### ISSUE THREAD

**Issue by graybeal** [cf-convention/cf-convention.github.io#24]
The CF Conventions site should have a clear contact point or mechanism on each page. Whether this is the CF mail list, or (I think better) a specific support email, having the info linked from each page will help people contact CF with issues.

**Comment by JonathanGregory** [comment]
I have included this in https://github.com/cf-convention/cf-convention.github.io/issues/162 so I will close this now. Please comment further there. Thanks for raising it, @graybeal.
