### ISSUE TITLE
Review and update CF "Software that uses CF" web page

### ISSUE THREAD

**Issue by ethanrd** [cf-convention/cf-convention.github.io#241]
An issue to start gathering ideas for updates and additions to the "Software that 'Understands' CF Data" [page](https://cfconventions.org/software.html).

In a [comment](https://github.com/cf-convention/discuss/issues/152#issuecomment-1228253721) on the 2022 CF Workshop Hackathon issue (cf-convention/discuss#152), @jypeter suggests adding

- PCMDI's cdms2 (maybe xCDAT?)
- Ferret and pyFerret
- Maybe some R packages

**Comment by ethanrd** [comment]
I recently stumbled over a 2012 netCDF workshop "Where is CF Metadata Used?" [page](https://www.unidata.ucar.edu/software/netcdf/workshops/most-recent/cf/Use.html) which mentions a no longer available PCMDI "Projects and Groups Adopting or Encouraging the CF-Conventions as a Standard" [page](http://cf-pcmdi.llnl.gov/projects-and-groups-adopting-the-cf-conventions-as-their-standard). The Wayback Machine's latest version is a [February 2013 copy](https://web.archive.org/web/20130213230013/http://cf-pcmdi.llnl.gov/projects-and-groups-adopting-the-cf-conventions-as-their-standard).

There's a good amount there which will likely require some review and maybe reaching out to some groups/projects.

It also has me wondering if the current CF software page shouldn't be expanded to include projects, groups, and maybe datasets being produced using CF.

**Comment by czender** [comment]
@ethanrd please start with that and then remind me at the workshop (perhaps at a relevant hackathon?) and I'll suggest some more CF-oriented text.

**Comment by kevin-obrien** [comment]
@ethanrd definitely should add PyFerret and ERDDAP.  Looks like a good hackathon, like @czender suggested..

**Comment by ethanrd** [comment]
The [netCDF software page](https://www.unidata.ucar.edu/software/netcdf/software.html) might be useful to review.

**Comment by ethanrd** [comment]
@ajheaps - Can we add [cf-view](http://ajheaps.github.io/cf-view/) to the CF software page?

**Comment by ethanrd** [comment]
@ajheaps and @davidhassell - I started drafting some Markdown text for adding cf-view to the CF software list. I was looking at the cf-view website but didn't find a description of what aspects of CF it supports. Do you have a suggestion for a sentence or two on what aspects of CF it uses/supports? Here's the Markdown text I have so far:
```
### cf-view - CF Python Quick Look Visualization Package
The [cf-view Python package](https://ajheaps.github.io/cf-view/) is a quick look data exploration tool for netCDF and Met Office PP data.
It uses the [cf-python](#cf-python---cf-python-package) and [cf-plot](#cf-python---cf-python-package) packages so is able to process any CF-compliant dataset.
```

**Comment by davidhassell** [comment]
Hi @ethanrd. Whilst cf-python can deals with anything, I'm not sure how cf-view view deals with non-spatiotemporal dimensions. I think that @ajheaps might be away for a bit, who'll know for sure, but I would say that if you are keen to close this then the bit of text that you have is fine, and we can always add more details later.

**Comment by ethanrd** [comment]
@davidhassell - I added the `cf-view` text above with a minor change to Charlie's PR (#266). I think it can be merged once someone checks that my change didn't break anything.

I added text for ERDDAP and (Py)Ferret in a new PR (#291). I'll ask for review there.

**Comment by ethanrd** [comment]
I'm reopening this issue as there's a second PR attached to it that is still open.

**Comment by JonathanGregory** [comment]
@ethanrd, what shall we do about https://github.com/cf-convention/cf-convention.github.io/pull/291 (Add to the CF software list (ERDDAP and Ferret/PyFerret)?

**Comment by ethanrd** [comment]
@JonathanGregory - I think we can merge it. I spoke with Kevin about this awhile back and he was good with it.

**Comment by ethanrd** [comment]
It has some conflicts with the main branch. I'll fix that and merge and we can go from there.
