### ISSUE TITLE
update end of David Hassell's term on the committee

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#246]
Please could someone (for instance, @davidhassell :smiley:) check and merge [PR #245](https://github.com/cf-convention/cf-convention.github.io/pull/245). It has been agreed by the governance panel so it can be merged immediately. Thanks.

**Comment by erget** [comment]
I'll leave this honour to @davidhassell - congratulations and thanks for your valuable contributions! 👏

**Comment by davidhassell** [comment]
Well, you're too kind! Thank you to to governance panel - I'm always happy to help. Merging now ...
