### ISSUE TITLE
delete spam trac tickets

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#248]
For a brief period trac accepted tickets from bogus sources, with the result that tickets 120-137 inclusive are spam. I have prepared [PR #247](https://github.com/cf-convention/cf-convention.github.io/pull/247) to delete them. Please could someone check and merge it. Thanks. Proposals to fix defects must be approved by a member of the Conventions Committee and Standard Names Committee, or the Governance Panel. They can be merged immediately thereafter.

**Comment by larsbarring** [comment]
Just  a thought: would it be useful to include a brief sentence stating something like "Tickets 120-137 were spam and consequently deleted", just for keeping the history transparent?

**Comment by JonathanGregory** [comment]
@erget has noticed that ticket 123 is not spam, although in a spam sandwich. I will reinstate that one. Thanks, Daniel. I agree with you, @larsbarring, that the editing to the trac tickets should be noted. Thanks for your coment. I'll do that too.

**Comment by davidhassell** [comment]
This all looks good to me - thanks, Jonathan.

**Comment by JonathanGregory** [comment]
I have reinstated ticket 123 and modified the index and navigation accordingly. I have inserted a note at the top of the index about the manual editing. Also I have made other manual edits to make the index look properly like a standalone static web page (instead of a Trac query) and remove all the inactive links.

**Comment by erget** [comment]
Thanks @JonathanGregory , I've merged and done some git incantations.

**Comment by JonathanGregory** [comment]
Thanks @erget. I found that I had not correctly fixed the navigation between tickets in the HTML (because they appeared in two places and I modified the wrong one) so I prepared and merged [another PR](https://github.com/cf-convention/cf-convention.github.io/pull/249) just now. It works properly now. Hence, I think this task is complete and I'm closing the issue.
