### ISSUE TITLE
Keywords to references not shown in the pdf version of the reference list

### ISSUE THREAD

**Issue by larsbarring** [cf-convention/cf-convention.github.io#250]
In the HTML version of the Conventions document the "keywords" are shown as expected in the reference list, but not in the PDF version. See this example:

HTML:
> ▪ [NetCDF][ NetCDF Software Package](http://www.unidata.ucar.edu/netcdf/index.html) . UNIDATA Program Center of the University Corporation for Atmospheric Research

PDF:
> ▪ [] [NetCDF Software Package](http://www.unidata.ucar.edu/netcdf/index.html) . UNIDATA Program Center of the University Corporation for Atmospheric Research .

**Comment by JonathanGregory** [comment]
Dear @larsbarring

Thanks for pointing this out. I am going to repost it in David's [open discuss issue](https://github.com/cf-convention/discuss/issues/169) on the release just made. I hope that's OK.

Jonathan
