### ISSUE TITLE
Mention (provide) some actual test files on the website

### ISSUE THREAD

**Issue by jypeter** [cf-convention/cf-convention.github.io#257]
A quick question (but answering may take some time), following a coffee discussion I have with @oliviermarti
 this morning : does the CF convention site provide netCDF test/example files?

- There is no mention of test files in the _Quick Links_ section on the [home page](http://cfconventions.org/)
- I have searched `test` in the [Latest release](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html) page of the documentation: there are 19 occurrences of `test`, but nothing about _test files_
- There are more occurrences of `example` and `sample`, but the few I have checked did not seem to be _example files_ or _sample files_
- I have just noticed that there is [no mention of CMIP or ESGF in the CF convention](https://github.com/cf-convention/cf-convention.github.io/issues/256), in case someone answers here that people could just grab files from ESGF

The document does provide some example text dumps of netCDF files headers, but having easy access to actual test files could be useful for:
- end user who want to look at actual files following CF, and play with them
- developers who want to check if their tools can handle the CF convention (at least partly)

I have recently started [another thread about test files](https://github.com/xCDAT/xcdat/issues/277)

**Comment by JonathanGregory** [comment]
Dear @jypeter 

Thanks for your posting. Indeed, there are no test files, although the rules have always called for them. [Conventions issue #348](https://github.com/cf-convention/cf-conventions/issues/348) raised by @atmodatcode earlier this year is closely related. If you don't mind, I would suggest that this discussion should continue on that issue instead, where I will repost your comment, to avoid duplication.

Best wishes

Jonathan

**Comment by jypeter** [comment]
Thanks for merging these similar issues
