### ISSUE TITLE
black header hides page content (overlays on top of it)

### ISSUE THREAD

**Issue by graybeal** [cf-convention/cf-convention.github.io#26]
The black CF MetaData header is styled in such a way that it obscures the actual content of the page. This is worked around in most of the pages by leaving several blanks lines at the top of the page. 

But when you are linking to content within a page (anchored content), the browser puts the anchor at the top of the page, which is behind the top border. Users will be confused because they won't see the section title that they just tried to jump to.

To make the anchor links work as expected throughout the pages, it will be necessary to fix the styling on the header.

**Comment by taylor13** [comment]
Has this pull request been submitted?

**Comment by JonathanGregory** [comment]
I don't know whether this has been done. If no-one else knows, I suggest we close this issue in three weeks from now (on 29th September).

**Comment by ethanrd** [comment]
The issue does not appear to be fixed. Navigating to an [anchor on the governance page](https://cfconventions.org/governance.html#information-management-and-support), the title at the anchor is covered by the nav header.

Does anyone on the @cf-convention/info-mgmt team (or anyone else) know CSS well enough to see if there is an easy fix for this for this issue?

**Comment by rhattersley** [comment]
The navigation header varies in height depending on the width of the browser window (e.g. on a mobile device) so a fixed size offset can't work consistently.

I suggest either:

1. Move the vertical scroll bar down to the "container" div (e.g. by setting `height: 100%` on the `html` and `body` elements and `height: 100%; overflow-y: scroll` on the "container" div. You might also want to nest the content within another div to allow the scroll bar to stay on the far right of the screen.)
2. Simply stop the navigation header being fixed to the top of the window. It's simpler overall (easier to maintain, less likely to go wrong on random browser X, etc.) and doesn't really detract from the ease of use of the site.

(If you do decide to stick with a fixed position header and a fixed size offset then setting the [scroll-padding-top](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-top) property on the html element should be the easiest way.)

**Comment by JonathanGregory** [comment]
Dear @rhattersley 

Thanks for explaining. I agree that the second option is better. I don't know which bit of the code does that. I suppose it must be in this block from `_layouts/default.hml`.

```
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
          </button>
          <a class="navbar-brand" href="/index.html"><img src="/Data/media/images/logo.png" style="position: relative; top: -10px"/></a><a class="navbar-brand" href="/index.html">CF MetaData</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% assign pages_list = site.pages %}
            {% assign group = 'navigation' %}
            {% include pages_list %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
```

Is `style="position: relative; top: -10px"` the thing which fixes it there, perhaps?

Do you know if there's a way to see what a GitHub-generated website will look like from a pull request, before merging it and it goes live?

Best wishes

Jonathan

**Comment by rhattersley** [comment]
To remove the fixed aspect I think it's just:
* Remove the `navbar-fixed-top` class from the navbar div.
* Remove the `padding-top` from the body.
* Force the "margin-bottom" to zero on the navbar div.

All of which are controlled in `_layouts/default.html` as you had identified.

I'm not aware of any _simple_ way of having a preview version of a Pages site for a pull request, but if you want to be thorough and don't mind the complexity... thanks to a GitHub workflow that's been [defined for this repo](https://github.com/cf-convention/cf-convention.github.io/blob/master/.github/workflows/check_jekyll_build.yml), you can download a built version of the site for each pull request by navigating to the "Actions" tab and then finding the relevant "Check Jekyll Build" run, e.g. https://github.com/cf-convention/cf-convention.github.io/actions/runs/1214286324 is currently the latest run for pull request #161. At the bottom of which there's a 600+ MB "CF Website" zip file you can download and then preview.

For a simple change like this though, I would just use the developer tools in Firefox/Chrome (Ctrl+Shift+I) to dynamically explore & modify the contents of the page and then translate that back to the repo content.

**Comment by JonathanGregory** [comment]
Well, it's easy when you know how! But I certainly didn't. Thanks @rhattersley for your prescription for the navigation bar. I have implemented this in https://github.com/cf-convention/cf-convention.github.io/pull/161.

**Comment by JonathanGregory** [comment]
Daniel @erget proposes to merge https://github.com/cf-convention/cf-convention.github.io/issues/162, which includes this change, and no-one has objected here or there, so I'll close this issue now.
