### ISSUE TITLE
additions to list of CF contributors

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#265]
Dan Nowacki, USGS, should be added to the [list](http://cfconventions.org/conventions_contributors.html) in view of his initiating [removal of extraneous space after asciidoc formatting](https://github.com/cf-convention/cf-conventions/issues/381).

**Comment by davidhassell** [comment]
Definitely, thanks. I wonder if we could add a "contributor" label to issues/PRs to make these easy to find later in the year?

**Comment by JonathanGregory** [comment]
Yes, we could. The _New contributor_ label should be added when an issue is closed, along with either _Change agreed_ or _No change agreed_.

**Comment by davidhassell** [comment]
A `new contributor` label now exists.

**Comment by JonathanGregory** [comment]
Thank you for doing that, David. I have slightly clarified its description to say it's new contributors to the _conventions_ (not the standard names). Also I have created the same label, with the same colour, in the `conventions` repo, where most of them will come from.

**Comment by JonathanGregory** [comment]
Following the CF meeting hackathon, and from looking through 2002-2005 in the email archive, I believe that the following should be added to the list of contributors:

* Jesus Fernandez, Universidad de Cantabria
* Magnus Hagdorn, University of Edinburgh
* Angelika Heil, DKRZ
* Steve Jones, University of Bergen
* Luis Kornblueh, MPIM
* Dan Nowacki, USGS
* Jean-Yves Peterschmitt, LSCE-CEA-IPSL
* Burkhardt Rockel, GKSS
* Ag Stephens, BADC

Jonathan

**Comment by JonathanGregory** [comment]
No comments have been raised for three weeks on this issue, which is therefore agreed. Please could someone check and merge [PR #300](https://github.com/cf-convention/cf-convention.github.io/pull/300), which implements this change by adding more individuals to the list of contributors to the conventions. Thanks.
