### ISSUE TITLE
Allow CF standard name units to be searched in HTML pages

### ISSUE THREAD

**Issue by srstsavage** [cf-convention/cf-convention.github.io#27]
_The functionality discussed in this issue has been implemented by @bzah in_ [this pull request](https://github.com/cf-convention/cf-convention.github.io/pull/218) _in response to_ [this later similar issue](https://github.com/cf-convention/cf-convention.github.io/issues/200).

It would be useful (for me, anyway) to be able to search units on the [CF standard name HTML pages](http://cfconventions.org/Data/cf-standard-names/27/build/cf-standard-name-table.html). This can help narrow down the list if you're searching for a standard name to match an existing parameter in a data set (although you might have to try a few convertible units).

I would make a pull request on [cf-standard-name-table.xsl](https://github.com/cf-convention/cf-convention.github.io/blob/master/Data/cf-standard-names/22/xsl/html/cf-standard-name-table.xsl) but I can't find a master version, just copies that stop appearing in the [cf-standard-names folders](https://github.com/cf-convention/cf-convention.github.io/tree/master/Data/cf-standard-names) after version 22. Am I missing it?

**Comment by erget** [comment]
This looks stale - I'm closing it but please re-open if relevant!

**Comment by JonathanGregory** [comment]
Reopening because of pending [pull request](https://github.com/cf-convention/cf-convention.github.io/pull/218) to implement such a change.
