### ISSUE TITLE
Incorporate emails from 2002-2005 in `mailing-list-archive` and add information to README

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#273]
In the [current version of the mailing list archive](https://cfconventions.org/mailing-list-archive/Data/) we have years 2006-2019. I have obtained 2002-2005 from the NCAR archive, which is now back online, and incorporated them into the GitHub archive, making it complete, since the mailing list was set up in 2002. In the `README` file of the repo, I have recorded how the GitHub archive is made and presented on the web.

This is implemented in [PR #4](https://github.com/cf-convention/mailing-list-archive/pull/4) of the `mailing-list-archive` repo. You can see what it would look like from my copy of the repo: [README](https://jonathangregory.github.io/mailing-list-archive) and [mailing list archive](https://jonathangregory.github.io/mailing-list-archive/Data).

What do you think?

_Enhancement proposals must be approved by a member of the Information Management and Support Team, the Conventions Committee and Standard Names Committee, or the Governance Panel.
A proposer cannot approve their own enhancement.
After three weeks have elapsed for comments, if no objections are raised, the proposal can be approved and the proposal merged._

**Comment by erget** [comment]
Thanks @JonathanGregory , I've merged.
