### ISSUE TITLE
Update FAQ on maintaining CF

### ISSUE THREAD

**Issue by erget** [cf-convention/cf-convention.github.io#296]
> The last section, "Maintaining the CF standard", needs some serious updating to bring it into the GitHub era. Or needs removing or to be replaced with a pointer to CONTRIBUTING.md and/or rules.md.

_Originally posted by @ethanrd in https://github.com/cf-convention/cf-convention.github.io/issues/278#issuecomment-1255158238_

Referring to `faq.md`.

I think this is a good idea too. Unfortunately I'm a bit short on time so won't get to it right away but am happy that it's been proposed, and will happily support it once I find a few minutes if nobody has in the interim!

**Comment by JonathanGregory** [comment]
I would say the same, and likewise would like to spend some time on the FAQ, when I can.

**Comment by sadielbartholomew** [comment]
I also agree, and maybe I can help a bit too (making suggestions here and there, perhaps reviewing an eventual PR, etc.).

**Comment by JonathanGregory** [comment]
The link checker repeatedly finds these broken links, which I'm recording here for reference, to be dealt with when time allows.

[faq.md]:
✗ [404] https://mailman.cgd.ucar.edu/pipermail/cf-metadata/2010/048064.html | Failed: Network error: Not Found
✗ [404] https://mailman.cgd.ucar.edu/pipermail/cf-metadata/2008/052705.html | Failed: Network error: Not Found
✗ [404] https://mailman.cgd.ucar.edu/pipermail/cf-metadata/2009/047768.html | Failed: Network error: Not Found
✗ [404] https://mailman.cgd.ucar.edu/pipermail/cf-metadata/2010/053657.html | Failed: Network error: Not Found
✗ [404] https://mailman.cgd.ucar.edu/pipermail/cf-metadata/2008/052334.html | Failed: Network error: Not Found
✗ [404] https://mailman.cgd.ucar.edu/pipermail/cf-metadata/2012/055875.html | Failed: Network error: Not Found

**Comment by DocOtak** [comment]
Possible mapping:
* https://mailman.cgd.ucar.edu/pipermail/cf-metadata/2010/048064.html
   * https://cfconventions.org/mailing-list-archive/Data/3450.html
* https://mailman.cgd.ucar.edu/pipermail/cf-metadata/2008/052705.html
  * https://cfconventions.org/mailing-list-archive/Data/2500.html
* https://mailman.cgd.ucar.edu/pipermail/cf-metadata/2009/047768.html
  * I couldn't find this, there is a single message from Rob in the list archive: https://cfconventions.org/mailing-list-archive/Data/3154.html
* https://mailman.cgd.ucar.edu/pipermail/cf-metadata/2010/053657.html
  * https://cfconventions.org/mailing-list-archive/Data/2517.html
* https://mailman.cgd.ucar.edu/pipermail/cf-metadata/2008/052334.html
  * https://cfconventions.org/mailing-list-archive/Data/2098.html
* https://mailman.cgd.ucar.edu/pipermail/cf-metadata/2012/055875.html
  * I couldn't really find this either, maybe: https://cfconventions.org/mailing-list-archive/Data/5543.html

**Comment by JonathanGregory** [comment]
Dear Andrew @DocOtak 

This is great! Thanks a lot for your time and effort. That's a big step towards fixing the final missing links.

I think the posting from Rob Raskin that you found is the correct one. The reference to it says "list post mention". He mentions it just in the last sentence, saying it's the subject of another communication. I too cannot find anything else from him about it, though Russ Rew mentioned something similar in https://cfconventions.org/mailing-list-archive/Data/0418.html. In this case, the link to the posting isn't useful, I would say, but the [document](https://wiki.earthdata.nasa.gov/download/attachments/50792120/SWEET_SPG.ppt?version=1&modificationDate=1435254939370&api=v2) could be of interest.

For the final one also, I think you have found the only possibility. Piasecki is not mentioned anywhere else. In this case, we don't have a link to the document concerned, so I suppose we might as well delete this item - would you agree?

I see that the FAQ mentions the `pipermail` archive in a few places. We should change them as well.

Best wishes

Jonathan

**Comment by JonathanGregory** [comment]
Dear Andrew @DocOtak 

I have prepared [PR 401](https://github.com/cf-convention/cf-convention.github.io/pull/401) to replace the mailing list links, and remove some other references to the mailing list. There are plenty of other updates of content needed, but I didn't change anything else, except for referring to the CF repos in a consistent way. I believe that once these changes are implemented, the website won't have any missing links.

Would you mind checking the PR? I would be grateful. Thanks for your work on this issue.

Cheers

Jonathan

**Comment by JonathanGregory** [comment]
Dear all

I'm rather keen to see whether [this PR](https://github.com/cf-convention/cf-convention.github.io/pull/401) fixes the remaining broken links on the website, which are all in the FAQ, so I'd be happy if anyone has a minute to check and merge it if it looks OK. It implements the fixes that @DocOtak helpfully identified.

Thanks

Jonathan

**Comment by erget** [comment]
Thanks all for the hard work - it looks good for me so I will merge.

**Comment by JonathanGregory** [comment]
Thanks, @erget

**Comment by DocOtak** [comment]
Glad to see my suggestions go in, thanks for doing it @JonathanGregory
