### ISSUE TITLE
Broken link on html version of standard_name table.

### ISSUE THREAD

**Issue by MaartenSneepKNMI** [cf-convention/cf-convention.github.io#30]
At the top of the standard names table (version 27, html edition):

http://cfconventions.org/Data/cf-standard-names/27/build/cf-standard-name-table.html

there is a link to the 'Guidelines for Construction of CF Standard Names', which sounds like a useful document. 

Unfortunately the link:
http://cf-pcmdi.llnl.gov/documents/cf-standard-names/guidelines
points to the old site, and is currently unavailable. 

The file is available in github, it is just that the link is broken.

https://github.com/cf-convention/cf-convention.github.io/blob/master/Data/cf-standard-names/docs/guidelines.html

Thanks.

**Comment by taylor13** [comment]
The link seems to have been repaired.  I think we can close this issue.

**Comment by japamment** [comment]
The html pages for all versions of the standard name table, past and present, now link to the GitHub site, so this issue is fixed.
