### ISSUE TITLE
Guidance on proposing new standard names

### ISSUE THREAD

**Issue by taylor13** [cf-convention/cf-convention.github.io#319]
To help users construct new standard names consistent with established names, I think the [new issue form](https://github.com/cf-convention/discuss/issues/new?assignees=&labels=standard+name&template=standard-names.md&title=+Standard+names%3A+%2Aadd+your+own+title+here%2A) should include following its first sentence a link to http://cfconventions.org/Data/cf-standard-names/docs/guidelines.html.  It might read: 

"Before submitting an issue, be sure you have read and understood the [rules for vocabulary changes](http://cfconventions.org/standard_name_rules.html) and review the [guidance for constructing standard names](http://cfconventions.org/Data/cf-standard-names/docs/guidelines.html)."

**Comment by JonathanGregory** [comment]
I think that's a good idea. Thanks.

**Comment by feggleton** [comment]
I agree, thanks for spotting. I have changed the issue template in the discuss repo to reflect that change. Thanks Jonathan for bringing this ticket to my attention.
