### ISSUE TITLE
Web access to CF Compliance Checkers not reachable

### ISSUE THREAD

**Issue by ethanrd** [cf-convention/cf-convention.github.io#350]
The [CF compliance checker](https://pumatest.nerc.ac.uk/cgi-bin/cf-checker.pl) listed on the conventions [page](https://cfconventions.org/conventions.html) is not reachable. Same for the CF [compliance checker](http://wps-web1.ceda.ac.uk/submit/form?proc_id=CFChecker) listed on the "Software that works with CF" [page](https://cfconventions.org/software.html).

Does anyone know if these are down temporarily or if they have moved?

**Comment by RosalynHatcher** [comment]
Hi Ethan,

Sorry it's down temporarily after the server died. I'm in the process of bringing up a new dedicated VM and frontend.  
Hopefully in the next week or so.

Cheers,
Ros

**Comment by ethanrd** [comment]
Hi Ros,

Sounds good. Will the new server have the same address as before? Actually, there are two different server addresses. The conventions page lists a server at `pumatest.nerc.ac.uk` while the software page lists a server at `wps-web1.ceda.ac.uk`.

Hmm, the software page is written to point to a server at NCAS and another at CEDA. However, the NCAS link is actually to the GH repo.

I'm happy to make a PR to update things if you can tell me what address is correct and if there will be one at NCAS and one at CEDA.

Cheers,
Ethan

**Comment by JonathanGregory** [comment]
Ros has supplied a new URL for the cf-checker. I have prepared [this pull request](https://github.com/cf-convention/cf-convention.github.io/pull/372) to make the required changes.

**Comment by ethanrd** [comment]
Closing as fixed by #372.
