### ISSUE TITLE
Add xcdat to the Software page

### ISSUE THREAD

**Issue by jypeter** [cf-convention/cf-convention.github.io#361]
I have just noticed that the [Software that “Understands” CF Data](http://cfconventions.org/software.html) page does not mention [Xarray Climate Data Analysis Tools  (xCDAT)](https://xcdat.readthedocs.io/)

Can @tomvothecoder suggest what should be added?

**Comment by tomvothecoder** [comment]
Hey @jypeter thanks for the mention. Here's a description of xCDAT taken from the [README](https://github.com/xCDAT/xcdat#readme).

> xCDAT - Python package for climate data analysis on structured grids
> 
> xCDAT (Xarray Climate Data Analysis Tools) is an extension of [xarray](https://github.com/pydata/xarray) for climate data analysis on structured grids. It serves as a modern successor to the Community Data Analysis Tools ([CDAT](https://github.com/CDAT/cdat)) library. The goal of xCDAT is to provide generalizable features and utilities for simple and robust analysis of climate data. xCDAT's design philosophy is focused on reducing the overhead required to accomplish certain tasks in xarray. xCDAT aims to be compatible with structured grids that are [CF-compliant](https://cfconventions.org/) (e.g., CMIP6). Some key xCDAT features are inspired by or ported from the core CDAT library, while others leverage powerful libraries in the xarray ecosystem (e.g., [xESMF](https://pangeo-xesmf.readthedocs.io/en/latest/) and [cf_xarray](https://cf-xarray.readthedocs.io/en/latest/index.html)) to deliver robust APIs.
> 

I also think [CF-xarray](https://cf-xarray.readthedocs.io/en/latest/index.html) should be added to the list since that is what xCDAT uses to interpret CF metadata (tagging @dcherian so he is aware).

> CF-xarray - Python package for interpreting CF metadata on xarray objects
> 
> cf_xarray mainly provides an accessor (DataArray.cf or Dataset.cf) that allows you to interpret [Climate and Forecast metadata convention](http://cfconventions.org/) attributes present on [xarray](https://xarray.pydata.org/) objects.
>

**Comment by larsbarring** [comment]
A pull request with with the suggested additions would be welcome. Would you @jypeter and/or @tomvothecoder would mind doing this?

**Comment by jypeter** [comment]
@tomvothecoder can probably do this easily. The only feature I use in GH is _creating (or contributing to) issues_ :-)

**Comment by tomvothecoder** [comment]
Thanks for the consideration and I'll take a look at this!
