### ISSUE TITLE
Updated a broken link to UDUNITS examples of how to format units strings

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#373]
@larsbarring has corrected a broken link in the FAQ to UDUNITS. His [pull request](https://github.com/cf-convention/cf-convention.github.io/pull/371) will be merged if no-one objects in three weeks. Thanks, Lars.

**Comment by DocOtak** [comment]
Since this is a correction to the website faq and not one of the conventions documents, I don't think the 3 week wait applies to this. i.e. I think you can merge immediately

**Comment by DocOtak** [comment]
@JonathanGregory I see. I think there is a category of changes, such as this one, that we should be able to move faster on but not sure quite how to articulate it. In this case, it is the same content, just the location/url moved, which is something that, despite what [should happen](https://www.w3.org/Provider/Style/URI.html), is fairly normal on the internet.

**Comment by JonathanGregory** [comment]
Thanks for your comment, @DocOtak. I agree we should consider the rules for website updates. There are outstanding issues about this. Jonathan
