### ISSUE TITLE
Add Abel Aoun to the list of contributors to information management

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#376]
I have prepared [this pull request](https://github.com/cf-convention/cf-convention.github.io/pull/375) to add Abel Aoun @bzah to the [list of contributors to information management](http://cfconventions.org/infomgmt_contributors.html) in recognition of his [useful enhancements](https://github.com/cf-convention/cf-convention.github.io/pull/218) to the search facilities in the standard name table.

Updates to the website must be approved by a member of the Conventions Committee and Standard Names Committee, the Governance Panel, or someone to whom they have delegated this responsibility.
Updates should reflect decisions that have already been made by the Governance Panel or one of the Committees.
They can be merged immediately after approval.

**Comment by japamment** [comment]
Pull request merged and closed.
