### ISSUE TITLE
Look and feel for standard name table

### ISSUE THREAD

**Issue by bzah** [cf-convention/cf-convention.github.io#405]
I would like to see the standard name table to be more user friendly with some CSS.

- In particular, as first stated by @sadielbartholomew in #130, the table lacks spacing & looks cluttered.
I would also add that links (the `<a>` tag) were used to show that elements can be clicked in the table, but it's not a best practice to use links if something is not actually a link. It's would be fairly simple to add some css to improve how interactive the table is.
- There is also a broken link to unidata website.
- Plus, when I did #218, I used some javascript that can easily be replaced by HTML5, which is often cleaner and easier to work with.

I already made a PR to fix these: #404.
The changes are displayed on a github page here: https://bzah.github.io/cf-convention.github.io/Data/cf-standard-names/current/build/cf-standard-name-table.html
The xsl file was updated and the html page was generated using the Makefile.

**Comment by larsbarring** [comment]
I like this style change. 

Personally, I would like to see the triangle icon to the left on each row go away. If I find a subset of standard names, via a search, it happens that I would like to copy/paste the resulting table (including the description) into a spreadsheet (as was done when preparing [discuss/#262](https://github.com/cf-convention/discuss/issues/262)) and then the icons come along and are difficult to remove in the spreadsheet.

**Comment by JonathanGregory** [comment]
Dear Abel @bzah 

Thanks for doing this. I too think it looks better than before. I think it would be fine to remove the triangles on the left, as Lars suggests, because it's obvious whether you are displaying the description or not  - unless there is no description. Are there any such cases?

If you are willing to consider further style changes, I would say that I don't like the lines that delimit all the cells of the table. They are needed for the rows, but the columns are obvious. To guide one's eye along the rows, it might be look nicer to use a style with alternating shaded/unshaded rows. Also, I would left-justify the column headings, to match the contents, rather than centering them.

Best wishes

Jonathan

**Comment by bzah** [comment]
Hi,
@larsbarring, I guess it's quite tedious to filter, then open every description, then copy, then paste and format.
I believe what you ultimately want is an export function no ?
It would be much easier to just remove the icon, but perhaps it's worth opening a dedicated issue for adding an export to csv button.

@JonathanGregory Removing border and having strips was also suggested in #130 and it seems people agreed it would look nicer. 

I'm off for a few days, I will take care of these changes when I'm back.

**Comment by larsbarring** [comment]
Hi Abel @bzah 
Thanks for all these improvements, and for suggesting an export function. 

In one sense it would be good to have such an export  functionality, but on the other hand I am not sure whether it is worth investing the time. As always with computers, and not least web pages, it is possible to do "anything", the imagination  is the limit. In this case I personally do not think it is worth spending the time in developing such a functionality. Looking back I might have needed it only very few times (probably only two or three....). Moreover, I think that we do not want complexity that might be difficult to maintain over time if not serving an expressed need.

**Comment by bzah** [comment]
Hi Lars, Jonathan, I made an update ([see here](https://bzah.github.io/cf-convention.github.io/Data/cf-standard-names/current/build/cf-standard-name-table.html)).

What do you think ?

**Comment by larsbarring** [comment]
This looks all good to me. Many thanks Abel!

**Comment by JonathanGregory** [comment]
I think it's much better, Abel @bzah. Thanks a lot.

**Comment by bzah** [comment]
I will rebase my changes and refresh the html, that should fix the conflicts on it.

**Comment by larsbarring** [comment]
Closed as completed via #404

**Comment by larsbarring** [comment]
Hm, it looks like the changes are not visible at the [usual place](https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html). Maybe I was too quick to merge, and/or something more has to be done @japamment, @sadielbartholomew, @bzah ?

**Comment by bzah** [comment]
Hi Lars, I guess it's because the html page is not yet generated.
One would need to run the makefile in Data/cf-standard-names/current to generate the new html page, but I don't know how it is published to https://cfconventions.org afterwards.

**Comment by larsbarring** [comment]
OK, then I will leave this to the the experts directly involved in the standard names workflow :-)

**Comment by bzah** [comment]
Hi @japamment, should I have committed and pushed the html document as well to make the changes appear in on CF website ?
Or is there another process that will publish the page ?

**Comment by sadielbartholomew** [comment]
Hi all, I don't have time right now, or indeed soon, to investigate why the style changes haven't manifested, but to add, **please don't push any HTML manually** - as others have suggested, that HTML should be auto-generated by some means (and if we add any manually it will get overwritten each time to overwrite the changes else be static with the changes, but we need it to be able to be generated with updates too). But I am not sure of the process we use for that. Hopefully Alison can clarify.

**Comment by bzah** [comment]
I'm closing this issue as the changes have been deployed, thanks everyone!
