### ISSUE TITLE
add a link to xml source of current standard name table

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#408]
In [discuss issue 195](https://github.com/cf-convention/discuss/issues/195), Luke @lhmarsden pointed to https://cfconventions.org/Data/cf-standard-names/current/src/cf-standard-name-table.xml as the URL of the xml source for the _current_ version of the standard name table (whatever that version is). If this is a future-proof reliable location for software to refer to, it would be good to add a link to it somewhere on the website. If there is one, I haven't found it.

**Comment by larsbarring** [comment]
I imagine that this might be fairly easily solved. Currently, the upper part of the [vocabularies web page](https://cfconventions.org/vocabularies.html) is

![image](https://github.com/cf-convention/cf-convention.github.io/assets/15440426/098c57a4-dd0d-4d88-8cb2-9f68beaff7b5)


where the links under the upper heading ("... current version ...) go to numbered versions, such as `..../83/....`, where the numbers could easily be changed to ` ..../current/....`. And one could then consider to include links to the numbered versions (actually pointing to the same as current) under each of the heading below. The upper heading that now reads
"Standard Name Table (current version, v83, 17 October 2023)" could then be  changed to read either "Standard Name Table (current version~~, v83,~~ 17 October 2023". 

As I have no insight into the workflow for creating and publishing new versions of the standard name table I leave this as a suggestion for others to consider if/how to practically implement (ping @efisher008, @japamment, @sadielbartholomew).

**Comment by larsbarring** [comment]
I have now created a PR implementing the idea put forth in the previous comment. Additionally, the PR fixes some typos noted [elsewhere](https://github.com/cf-convention/cf-convention.github.io/issues/469#issuecomment-2016945535): bad link to Rules for updating, and v83 links  pointing to another version.

Test webpages are available [here](https://larsbarring.github.io/cf-convention.github.io/vocabularies.html). Comments regarding style and layout are most welcome. 

As there has been no comments to the suggestion for about 5 months, and support in the form of a "thumbs up" from @sadielbartholomew I think that maybe this PR can be merged soon to fix typos etc. if there are no comments (except minor changes to the style and layout). 

ping @japamment, @efisher008, @JonathanGregory , @sadielbartholomew

**Comment by JonathanGregory** [comment]
Thanks for the PR, @larsbarring. I agree that the change proposed by this issue has been agreed. (Actually, for reference, we have said somewhere that thumbs-up does _not_ count as explicit support for an `enhancement`. You have to say something to be counted. I think that's a good rule, but this is something we should discuss again when reviewing the rules, as needs to be done.) Also, the errors were reported as defects to be corrected more than three weeks ago, and no-one objected.

I think the PR is fine, except that the KWIK link doesn't work, because actually the KWIK index of the current version is not present in https://cfconventions.org/Data/cf-standard-names/current/build/kwic_index_for_cf_standard_names.html.

**Comment by larsbarring** [comment]
Thanks Jonathan, 

Regarding counting thumbs-up or not, I have nothing against not counting them. It might even be good, because a thumbs-up is a bit vague as support ( I thought that it would pass for this particular PR, because it is a rather limited change that I would judge as rather uncontroversial). 

Good that you spotted the non-working KWIC index!! 
Now fixed.

**Comment by JonathanGregory** [comment]
Thanks for your quick KWIC fix, Lars. (That sounds like Dr Seuss speaking.) I will merge it now, which closes this issue.
