### ISSUE TITLE
Add a **Release highlight** page

### ISSUE THREAD

**Issue by larsbarring** [cf-convention/cf-convention.github.io#429]
The just released version 1.11 includes 33 changes according to the Revision history (and even more, 57, if one looks at the github release page). But a majority are technical/language fixes or improvements of little interest to users of the conventions document. In the worst case important enhancements or changes may go unnoticed. 

From my very own tentative assessment about half of the entries in the Revision history are of little interest to the reader/user (other than perhaps a vague feeling that "things are now clearer more easy to understand" :-) ) : 

> [Issue #481](https://github.com/cf-convention/cf-conventions/issues/481): Introduce `units_metadata` attribute and clarify some other aspects of units
    [Issue #147](https://github.com/cf-convention/cf-conventions/issues/458): Clarify the use of compressed dimensions in related variables
    ~~[Issue #486](https://github.com/cf-convention/cf-conventions/issues/486): Fix PDF formatting problems and invalid references~~
    ~~[Issue #490](https://github.com/cf-convention/cf-conventions/issues/490): Simple correction to Example 6.1.2~~
    ~~[Issue #457](https://github.com/cf-convention/cf-conventions/issues/457): Creation date of the draft Conventions document~~
    [Issue #445](https://github.com/cf-convention/cf-conventions/issues/445): Updates concerning the Polar Stereographic Grid Mapping
    [Issue #468](https://github.com/cf-convention/cf-conventions/issues/468): Update section 2.3 to clarify recommended character set
    [Issue #147](https://github.com/cf-convention/cf-conventions/issues/147): Clarify the use of compressed dimensions in related variables
    ~~[Issue #483](https://github.com/cf-convention/cf-conventions/issues/483): Add a missing author~~
    ~~[Issue #463](https://github.com/cf-convention/cf-conventions/issues/463): Convert URLs with HTTP protocol to HTTPS if available, fixed a few dead links~~
    ~~[Issue #383](https://github.com/cf-convention/cf-conventions/issues/383): Link to the CF website and deleted the Preface section~~Reference UGRID conventions in CF
    ~~[Issue #472](https://github.com/cf-convention/cf-conventions/issues/472): Fix incorrect formating for some <= symbols~~
    ~~[Issue #458](https://github.com/cf-convention/cf-conventions/issues/458): Fix broken link to Unidata documentation.~~
    [Issue #423](https://github.com/cf-convention/cf-conventions/issues/423): Always use "strictly monotonic" when describing coordinate variables
    ~~[Issue #420](https://github.com/cf-convention/cf-conventions/issues/420): Add List of Figures~~
    ~~[Issue #210](https://github.com/cf-convention/cf-conventions/issues/210): Correct errors in examples H9-H11~~
    [Issue #374](https://github.com/cf-convention/cf-conventions/issues/374): Clarify rules for packing and unpacking in Section 8.1
    ~~[Issue #449](https://github.com/cf-convention/cf-conventions/issues/449): Typo in end-date in Example 7.12~~
    ~~[Issue #266](https://github.com/cf-convention/cf-conventions/issues/266): Updates to some links in the bibliography~~
    ~~[Issue #286](https://github.com/cf-convention/cf-conventions/issues/286): Some labels of examples contain "Example" so that their label in the list of examples contains "Example" (affects four examples); corrected captions of three tables and five examples~~
    ~~[Issue #418](https://github.com/cf-convention/cf-conventions/issues/418): Add missing examples to TOE (table of examples); cof themorrected captions of three tables and three examples~~
    ~~[Issue #367](https://github.com/cf-convention/cf-conventions/issues/367): Delete obsolete references in section 3.3 for mappings of CF standard names to GRIB and PCMDI tables~~
    ~~[Issue #405](https://github.com/cf-convention/cf-conventions/issues/405): Update ch. 4.4 text on reference time vs. UDUNIT~~
    ~~[Issue #406](https://github.com/cf-convention/cf-conventions/issues/406): Remove duplicate section 8.2 in the conformance document~~
    ~~[Issue #391](https://github.com/cf-convention/cf-conventions/issues/391): Correct link to Snyder and typo in the bibliography~~
    ~~[Issue #437](https://github.com/cf-convention/cf-conventions/issues/437): Correct link to NUG in the bibliography~~
    [Issue #428](https://github.com/cf-convention/cf-conventions/issues/428): Recording deployment positions
    [Issue #430](https://github.com/cf-convention/cf-conventions/issues/430): Clarify the function of the cf_role attribute
    [Pull request #408](https://github.com/cf-convention/cf-conventions/pull/408): Deleted a sentence on "rotated Mercator" under Oblique Mercator grid mapping in Appendix F
    [Issue #265](https://github.com/cf-convention/cf-conventions/issues/265): Clarification of the requirements on bounds variable attributes
    [Issue #260](https://github.com/cf-convention/cf-conventions/issues/260): Clarify use of dimensionless units
    [Issue #410](https://github.com/cf-convention/cf-conventions/issues/410): Delete "on a spherical Earth" from the definition of the latitude_longitude grid mapping in Appendix F
    [Issue #153](https://github.com/cf-convention/cf-conventions/issues/153): Reference UGRID conventions in CF

The remaining ones could perhaps be divided into something like 
***"Major enhancements and new features"***
* Introduce `units_metadata` attribute and clarify some other aspects of units
* Reference UGRID conventions in CF

***"Clarifications"** (some of the listed items may not qualify?)*
* Clarify the use of compressed dimensions in related variables
* Updates concerning the Polar Stereographic Grid Mapping
* Update section 2.3 to clarify recommended character set
* Clarify the use of compressed dimensions in related variables
* Always use "strictly monotonic" when describing coordinate variables
* Clarify rules for packing and unpacking in Section 8.1
* Recording deployment positions
* Clarify the function of the cf_role attribute
* Deleted a sentence on "rotated Mercator" under Oblique Mercator grid mapping in Appendix F
* Clarification of the requirements on bounds variable attributes
* Clarify use of dimensionless units
* Delete "on a spherical Earth" from the definition of the latitude_longitude grid mapping in Appendix F

The "**Major enhancements and new features**" items should then be described with a few sentences that also refer to the relevant sections in the document. Similarly, the "**Clarifications**" items should be explained with a sentence, if possible lumping together related items, like for example the ones related to CRS/map projections (Polar Stereographic, rotated Mercator, and spherical Earth).

**Comment by larsbarring** [comment]
Dear @JonathanGregory 

I thought a about this for a while, but looking at the list of issues that have been closed now with 1.11 I think these two categories are not fine-grained enough. While I do admit tht ther eisa degree of value judgement and sa few boundary cases on the list above, I think that we can agree that most of the ones stricken over are not of interest to the readers/users, .e.g.
> ~~https://github.com/cf-convention/cf-conventions/issues/483: Add a missing author~~
~~https://github.com/cf-convention/cf-conventions/issues/463: Convert URLs with HTTP protocol to HTTPS if available, fixed a few dead links~~

just to pick two random ones. 

These do not need to be mentioned at all (I am not sure that all such are labelled `defect`, but this can of course be improved for the future). 

Then we have a middle category, which are the ones that I tentatively called "Clarifications". These  are relevant to briefly highlight because they do provide a clarification in relation to what has been discussed,or asked, or otherwise influence users' understanding and interpretation of the conventions. E.g. these ones:
> https://github.com/cf-convention/cf-conventions/issues/468: Update section 2.3 to clarify recommended character set
https://github.com/cf-convention/cf-conventions/issues/430: Clarify the function of the cf_role attribute
https://github.com/cf-convention/cf-conventions/issues/265: Clarification of the requirements on bounds variable attributes
https://github.com/cf-convention/cf-conventions/issues/260: Clarify use of dimensionless units
https://github.com/cf-convention/cf-conventions/issues/410: Delete "on a spherical Earth" from the definition of the latitude_longitude grid mapping in Appendix F

And then there are the (usually few) enhancements that add important new features or otherwise have more far-reaching consequences that should be highlighted. 

So, I do think that with three categories we can substantially improve this. Moreover, I understand that github have more advanced mechanisms for supporting and automating categorising issues/PRs into different types thus helping out with this. But I do not have any deeper insights in how it works.

**Comment by larsbarring** [comment]
Dear Jonathan,

I realise that did not express the idea I had in mind very well (rather the opposite I am afraid). The intention was not to focus on issue categories, but rather to highlight the essence of the new release in the **main webpage of cfconventions.org** (hence the issue title and having the issue in this repo).


What I intended is something like these two examples

Mockup 1:

-----------------------------

***Conventions***: **Latest release** (1.11) HTML PDF Highlights •  **Working draft** HTML PDF

***Vocabularies***: **Standard names**  •  **Area types**  •  **Standardized regions**

-----------------------------

where the "Highlights"  is a link to a summary of the major new elements in the release.


Mockup 2:

-----------------------------

***Conventions***: **Latest release** (1.11) HTML PDF  •  **Working draft** HTML PDF
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*Release Highlights*

***Vocabularies***: **Standard names**  •  **Area types**  •  **Standardized regions**

-----------------------------

And the same for the "*Release Highlight*"

-----------------------------

And the link points to a separate web page or, perhaps preferably, to a discuss/#issue that announces the new release. Something like this ("zero-order-draft"):

## Release of CF-1.11 

_A brief text as introduction, perhaps something like:_
The Climate and Forecasting Conventions has been update to version 1.11 on 2023-12-XX. The full document is available as [html](link-to-document) and as [PDF](link-to-document). Major new and improved features are highlighted below. Additionally, a number of minor technical and textual improvements have been made, see full details [here](link-to-html-revision-section).


### Highlights

* ***Units***: Several improvements and clarifications have been made in how CF deals `units`. A major new addition is the introduction of the strongly recommended attribute `units_context` that should be attached to a data variable involving temperature data. This attribute, which is only relevant for temperature data, can take one of these three values: `on_scale`, `difference`, or `unknown` (default). With this attribute a data producer can unambiguously express how the units of a data variable should be converted between `degree_Celsius`and `Kelvin`. Without this attribute, or if it is specified as `unknown`, such conversion is not always possible. See [section 3.1](link-to-section-3.1) for details. In addition, the use of dimensionless units as well as the relationship between CF and the UDUNITS software package has been clarified throughout the text.
* .... 
* ....
* ***Coordinate reference systems (CRS) and map projections***: [Appendix F ](link-to-Appendix-F) sees three clarifications and changes:
   * It is now clarified that the [Latitude-longitude](link) grid mapping is not limited only to spherical representation of the Earth.
   * The jargon term "rotated Mercator" is now removed from a comment under the [Oblique Mercator](link). THe reason is that it is ambiguous in relation to well-established terminology. Instead use either **Oblique Mercator** or **Transverse Mercator**.
   * For the [Polar stereographic](link) grid mapping the parameter `straight_vertical_longitude_from_pole` is deprecated in favor of `longitude_of_projection_origin`, which is consistent with what is used by CF for other grid mappings. In addition, it is clarified that the closest relevant `proj` library link is `stere`.
* ....
* ....

**Comment by JonathanGregory** [comment]
Dear @larsbarring 

Sorry I missed your point. I probably read the title of the issue, but forgot about it once I started reading your categorisation of the revisions included in 1.11! I agree that a web page of release notes would be useful, highlighting the changes which users should be made aware of. Not to be deterred from my theme, though (!), I would suggest that it's the `enhancement` issues that ought to be described in the highlights web page, while the `defect` issues do not need to be described because they do not change what users do. Moreover, the text to be contributed to the highlight page could be written in the revision history of the conventions document when the PR is prepared i.e. longer text than the one line we currently have for each issue. It would be better to write these as we go along, rather than waiting for the release, by which time their essence may have been forgotten. It would be an easy extra task on building the new version to make the highlights web page by copying the text from the revision history.

Best wishses

Jonathan
