### ISSUE TITLE
Governance web page is not formatted correctly

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#44]
The page about governance on the live website http://cfconventions.org/governance.html isn't correctly formatted at the top. It looks right when viewed at https://github.com/cf-convention/cf-convention.github.io/blob/master/governance.md. Is there something wrong with formatting?

Jonathan

**Comment by graybeal** [comment]
Jonathan,

FWIW, I took a quick look at this. I suspect the parsers aren’t exactly the same in the two cases.

I don’t have the set-up to push or test changes, but if I did I’d try adding a line between the top header and the h3 header, changing
#CF Governance
###Governance Documents
to
#CF Governance

###Governance Documents

By the way, your URLs lost all their periods (?!), so *that* didn’t work out so well. :-)

John

**Comment by mattben** [comment]
I've corrected the markdown 1f6fabb465ab415117b6fe14078ad82621622474 What does  `By the way, your URLs lost all their periods` mean? All the links on that page seem to work.

**Comment by daf** [comment]
@mattben, in github's email about this issue, the URLs that @JonathanGregory wrote have the periods removed (and the links are then broken), see this screenshot:

![2016-01-19-10 39 16](https://cloud.githubusercontent.com/assets/228715/12423342/fda9449e-be98-11e5-9e9b-7796d7b3dfd5.png)

Oddly enough they are fine when viewing this issue on github itself.

**Comment by mattben** [comment]
agh: okay i'm chalking that up as a github bug, and close this issue.
