### ISSUE TITLE
New member of Information Management and Support Team

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#443]
Following a decision of the governance panel (by email) I have prepared PR #442 to add Ellie Fisher to the list of members of the Information Management and Support Team on the [governance webpage](https://cfconventions.org/governance.html). Thanks for joining the team, Ellie @efisher008.

Please could a member of the panel or the committee check and merge the PR.

**Comment by ethanrd** [comment]
Thanks Jonathan @JonathanGregory ! Looks good. I have merged. I will also add/invite Ellie to the GH info-mgmt team.

**Comment by efisher008** [comment]
Hello @JonathanGregory and @ethanrd,

Thank you for your work on this! I'm looking forward to contributing to the CF community.

Best,
Ellie
