### ISSUE TITLE
Broken merge

### ISSUE THREAD

**Issue by mattben** [cf-convention/cf-convention.github.io#48]
missing files,

please cherry pick out of history

Data/cf-conventions/cf-conventions-1.0/xsl/template/titlepage.xsl
Data/cf-conventions/cf-conventions-1.1/xsl/template/titlepage.xsl
Data/cf-conventions/cf-conventions-1.2/xsl/template/titlepage.xsl
Data/cf-conventions/cf-conventions-1.3/xsl/template/titlepage.xsl
Data/cf-conventions/cf-conventions-1.7/docbooksrc/.svn/tmp/tempfile.tmp
Data/cf-conventions/cf-conventions-1.7/xsl/template/.svn/all-wcprops
Data/cf-conventions/cf-conventions-1.7/xsl/template/.svn/entries
Data/cf-conventions/cf-conventions-1.7/xsl/template/.svn/format
Data/cf-conventions/cf-conventions-1.7/xsl/template/.svn/text-base/titlepage.xsl.svn-base
Data/cf-conventions/cf-conventions-1.7/xsl/template/titlepage.xsl
Data/docbook-xsl-1.73.2/params/.svn/text-base/template.xml.svn-base
Data/docbook-xsl-1.73.2/params/template.xml
Data/docbook-xsl-1.73.2/roundtrip/.svn/prop-base/template.dot.svn-base
Data/docbook-xsl-1.73.2/roundtrip/.svn/text-base/template-pages.xml.svn-base
Data/docbook-xsl-1.73.2/roundtrip/.svn/text-base/template.dot.svn-base
Data/docbook-xsl-1.73.2/roundtrip/.svn/text-base/template.xml.svn-base
Data/docbook-xsl-1.73.2/roundtrip/template-pages.xml
Data/docbook-xsl-1.73.2/roundtrip/template.dot
Data/docbook-xsl-1.73.2/roundtrip/template.xml
Data/docbook-xsl-1.73.2/template/.svn/all-wcprops
Data/docbook-xsl-1.73.2/template/.svn/entries
Data/docbook-xsl-1.73.2/template/.svn/text-base/titlepage.xml.svn-base
Data/docbook-xsl-1.73.2/template/.svn/text-base/titlepage.xsl.svn-base
Data/docbook-xsl-1.73.2/template/titlepage.xml
Data/docbook-xsl-1.73.2/template/titlepage.xsl

**Comment by mattben** [comment]
fixed with https://github.com/cf-convention/cf-convention.github.io/commit/27212270577f724e9df10d4e23829a4128cd84fb

**Comment by JonathanGregory** [comment]
Thanks for sorting this out. I hope I won't cause such problems next time! Jonathan
