### ISSUE TITLE
Minor update to the newly added XML schema file  

### ISSUE THREAD

**Issue by larsbarring** [cf-convention/cf-convention.github.io#481]
There is a schema mismatch between the new XML element for the "first published date" in the XML file. The element was introduced in [cf-conventions/#511](https://github.com/cf-convention/cf-conventions/issues/511) as `first_published`, but was in the schema file written as `first_published_date`. The "_date" part is quite unnecessary and even not correct as the information carried by this element is in fact an xml dateTime object. 

See PR #482

**Comment by larsbarring** [comment]
Hi Sadie @sadielbartholomew: May I one last time ask you: this time to merge this PR #482, which is correcting a minor oversight on my part. After closing this, and [#516](https://github.com/cf-convention/cf-conventions/issues/516) everything the set to dig into #470 that will keep me busy for a while :-))

Many thanks,
Lars

**Comment by sadielbartholomew** [comment]
Good spot Lars. Sure, I will review it and merge if good now.
