### ISSUE TITLE
Add GDT and CF-beta conventions documents

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#508]
Recently I was asked for the text of the GDT netCDF convention, which was one of the bases for initial development of CF. In case this is useful in future, I propose to add a very short section to the [conventions page](https://cfconventions.org/conventions.html) on conventions that preceded CF 1.0, with links to new pages that provide the text of the various versions of GDT and the beta versions of CF. I've implemented this in PR #507.

Does anyone have any comments or objections?

I am trying to test whether I've formulated the pages correctly by requesting the GitHub Pages site https://jonathangregory.github.io/cf-convention.github.io to be generated from the [GDT branch](https://github.com/JonathanGregory/cf-convention.github.io/tree/GDT) of my GitHub repo. I've done this before successfully, but this time the build process is not producing html from the markdown files. For instance, https://jonathangregory.github.io/cf-convention.github.io/conventions.md is there, but https://jonathangregory.github.io/cf-convention.github.io/conventions.html is not. Why is this, can anyone explain? Thanks.

----

Enhancement proposals must be approved by a member of the Information Management and Support Team, the Conventions Committee and Standard Names Committee, or the Governance Panel.
A proposer cannot approve their own enhancement.
After three weeks have elapsed for comments, if no objections are raised, the proposal can be approved and the proposal merged.

**Comment by larsbarring** [comment]
I have not yet looked at the changes you suggest (hence I do not yet know what GDT stands for), but in general I think that it would be valuable having a short piece summarising the foundation and inspiration that CF started from.

Regarding your technical issue with building the web page, I had the same problem and after quite some fiddling I ended up merging (rebasing) my issue branch into *my own* main branch. When pushing this to my own github repo the web pages were automatically built into my own `gh-pages` branch that, after fetching, could be displayed locally using a browser. But pointing to the github link did not help because that only displays the http source. Before doing all this I created a local "backup-main" branch that I used to reset the main.

**Comment by JonathanGregory** [comment]
Dear @larsbarring and all

Thanks for your suggestions, Lars. I tried this, and indeed the html files were created in the `gh-pages` branch. To make them portable I would have to edit them (because the paths are wrong). So it seems that it makes the files, but does not deploy them, even though it says it has. I am baffled by the whole process.

In addition, while intending to put the files into my own main branch, I accidentally merged my PR, and have thus bypassed the approval process unintentionally. I'm sorry, everyone! But that means you can see what it looks like now in the live website at https://cfconventions.org/conventions.html. Please say if you comment or object. If it's not wanted, I can delete it again.

Best wishes

Jonathan

**Comment by cofinoa** [comment]
The GDT documents are "choking" the link checker, due to invalid UTF-8 encoding: #493 

This is something similar happening with old documents that I have disabled to be checked by the web link checker. 

I have to update the discussion about the web link checker and add some action on this.

**Comment by cofinoa** [comment]
More details on the "choking": 
https://github.com/cf-convention/cf-convention.github.io/actions/runs/10348579431/job/28641104873#step:4:44

**Comment by JonathanGregory** [comment]
Sorry about that, Antonio @cofinoa. It would be perfectly fine to exclude the GDT documents from the link checker, since these are certainly not going to change. Can you do that easily?

**Comment by cofinoa** [comment]
The CF-beta has plenty of broken links:
https://github.com/cf-convention/cf-convention.github.io/issues/493#issuecomment-2291061408

I have excluded both directories: `GDT` and `CF-beta`.

**Comment by JonathanGregory** [comment]
Thanks, Antonio, and sorry for the trouble. Broken links are unsurprising, since these are ancient documents, being preserved for the record. Paul Durack and Karl Taylor have just arranged for GDT to be given a DOI https://zenodo.org/doi/10.5281/zenodo.13314769.

**Comment by taylor13** [comment]
I support the changes needed to link to the historical documents as described above.  Thanks for all your work on this.

**Comment by JonathanGregory** [comment]
Thanks, Karl. In that case, since more than three weeks have passed, and there aren't any objections, I'll close this as accepted and implemented, with thanks again to Antonio for dealing with the fall-out for the link-checker.
