### ISSUE TITLE
Links used by `cfchecker` are dead

### ISSUE THREAD

**Issue by brendan-m-murphy** [cf-convention/cf-convention.github.io#555]
Before submitting an issue be sure you have read and understand the [contributing guidelines](https://github.com/cf-convention/cf-convention.github.io/blob/master/CONTRIBUTING.md).

Proposals to fix GitHub issues must be approved by a member of the Information Management and Support Team.
They can be merged immediately thereafter.

The link http://cfconventions.org/Data/standardized-region-list/standardized-region-list.xml is dead, which breaks `cfchecker`: https://github.com/cedadev/cf-checker/issues/113

**Comment by RosalynHatcher** [comment]
Looks like the file got deleted in commit 85d93e3a2544a616cbee7c4c97b30c18fe37a0a9 
@efisher008 Can it please be reinstated as soon as possible? 

Thanks
Cheers,
Ros.

**Comment by japamment** [comment]
@brendan-m-murphy @RosalynHatcher 

Thanks for raising this. @efisher008 and I were spring cleaning the region list directory during the recent update. Looks like we got a little over enthusiastic! The file is restored now.

Best wishes,
Alison

**Comment by RosalynHatcher** [comment]
Thanks @japamment.  
I confirm the CF Checker website is now working again as expected.

**Comment by efisher008** [comment]
[like]  Fisher, Ellie (STFC,RAL,RALSP) reacted to your message:
________________________________

**Comment by larsbarring** [comment]
Brendan @brendan-m-murphy, if I understand the comments right the problem you reported has now been resolved -- can we close this issue?

**Comment by brendan-m-murphy** [comment]
Yes, thanks for taking care of that so quickly!
