### ISSUE TITLE
harvesting for / notification about new version of cf-standard-names

### ISSUE THREAD

**Issue by carueda** [cf-convention/cf-convention.github.io#56]
The Ontology Registry and Repository (ORR) at https://mmisw.org has been maintaining an RDF version of the CF standard name vocabulary. Although the involved conversion and registration process is performed automatically, it still needs to be triggered manually, once we learn that a new CF version has been released.  This entry is to get some input about how we could proceed to automate this as well.

One initial idea is simply to put together a cronjob that checks for any new version. In contrast to the individual `<version-number>` directories, I notice there is a `current` directory as well, which seems like an appropriate place to directly check for the last version number, that is, by looking into https://github.com/cf-convention/cf-convention.github.io/blob/master/Data/cf-standard-names/current/src/cf-standard-name-table.xml.

One other possible mechanism it that we could provide an ORR-based URL that CF could enable in this repository as a "webhook" to be triggered whenever there's a new version released.

Worth noting, we also keep a NVS-ORR mapping ontology relating the ORR and the NVS RDF versions of CF.  This mapping is also generated as part of our automated process.  So, a relevant question (if appropriate here) is about how long does it usually take for the NVS version to be updated upon a new version of CF.

Any comments/suggestions would be greatly appreciated.

**Comment by painter1** [comment]
Probably the simplest suggestion would be your first idea, to periodically check for a new version, and then get the standard names from the "current" directory.  Alison Pamment updates the standard names frequently, perhaps every month or two.  An even simpler alternative would be to simply download the standard names from the "current" directory once a month.

BTW, there are other parts of the CF Conventions besides the standard names.

**Comment by carueda** [comment]
Thanks, I just set up a cronjob based on the "current" directory, and your comment serves me as confirmation that this location is maintained as part of the general updates when a new version is released.

Yes, there are other parts. I'll check with @graybeal re his conversion of the "area types" vocab.
