### ISSUE TITLE
'latest' page on the web site is TERRIBLY out-of-date

### ISSUE THREAD

**Issue by jypeter** [cf-convention/cf-convention.github.io#57]
Don't know if this is something for @mattben or @japamment, but I have followed a _latest_ link found on Google, and landed on: http://cfconventions.org/latest.html

This links to **v27** of _Standard Names Table_, when the actual latest version is **v50**. I have not checked if the other links on the latest page were better

As you can see below, I was looking for something pretty straightforward!

![image](https://user-images.githubusercontent.com/2785573/37524447-26753a60-292a-11e8-9416-3bb24e7f5de6.png)

**Comment by mattben** [comment]
I'm more than willing to contribute to the project again, feel free to assign me issues if you need any help with the web work.

**Comment by japamment** [comment]
Thanks for the offer of help - much appreciated. In fact I'm pretty tied up dealing with new standard names just now so please could you look at fixing the link? The one in my previous message should always point to the latest version.

**Comment by jypeter** [comment]
Congratulations on your amazing response time! I was not sure where I should report the problem, and I have therefore also just created #58

**Comment by taylor13** [comment]
The page no longer seems to be "terribly out of date", so perhaps this issue can be closed?

**Comment by jypeter** [comment]
You are correct, and I'm closing the issue

I have spotted a slightly related error when following the links, described in #66
