### ISSUE TITLE
CF web site does not say where to report web related issues

### ISSUE THREAD

**Issue by jypeter** [cf-convention/cf-convention.github.io#58]
I had to do some digging in order to find I could report CF web related problems this repository...

There is no obvious _Contact_ link or page on the http://cfconventions.org/ web site, so maybe you could add a link to the issue pages https://github.com/cf-convention/cf-convention.github.io/issues from the [CF Discussion page](http://cfconventions.org/discussion.html)

**Comment by JonathanGregory** [comment]
I have included this in https://github.com/cf-convention/cf-convention.github.io/issues/162 so I'll close this issue now. Thanks for raising it, @jypeter.
