### ISSUE TITLE
Need text and links to the github site from the web pages

### ISSUE THREAD

**Issue by taylor13** [cf-convention/cf-convention.github.io#65]
If someone wants to contribute to CF our web pages direct them to the mail list and the trac site, but not the github project site.  The website needs revision so people will know how to engage.

At the very least, a quick link should be included on http://cfconventions.org and a short explanation of how one contributes, including a link to the github CF project should appear on http://cfconventions.org/discussion.html .  Also, need links to 
https://github.com/cf-convention/cf-conventions/blob/master/CONTRIBUTING.md
and possibly
http://cfconventions.org/rules.html

**Comment by JonathanGregory** [comment]
I agree too with @taylor13 and @jypeter. In fact now we've moved from email and trac to GitHub for both, the website is definitely out of date. It should point to GitHub issues. Is someone already addressing this in another issue (or perhaps pull request)? If not, I will assemble a list of proposals in this issue, or perhaps a new issue to bring things together.

**Comment by JonathanGregory** [comment]
I have included this change in https://github.com/cf-convention/cf-convention.github.io/issues/162 so I will close this one now. Please comment there. Thanks, @taylor13 and @jypeter.
