### ISSUE TITLE
Version number problem for "Current Working Draft" ?

### ISSUE THREAD

**Issue by jypeter** [cf-convention/cf-convention.github.io#66]
When I follow the links from the [Latest CF Conventions Documents](http://cfconventions.org/latest.html) page to the html versions of the CF convention (I have not checked the pdf version)

- _Most Recent Release (v1.7)_ [Single HTML](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html) brings me to a page that has the expected **Version 1.7** in the header (after the list of contributors), and the footer says `Last updated 2017-08-01`
- but _Current Working Draft (v1.8)_ [Single HTML](http://cfconventions.org/cf-conventions/cf-conventions.html) brings me to a page that has **also Version 1.7** in the header, when you would expect _1.8_ or _1.8 draft_ . The footer of the draft correctly shows a different date, `Last updated 2017-08-15`

**Comment by JonathanGregory** [comment]
I think the "latest version" links are correct now. Do you agree, @jypeter? If so, can we close this?

**Comment by jypeter** [comment]
Thanks! Looks good now
