### ISSUE TITLE
How to cite/acknowledge the CF convention?

### ISSUE THREAD

**Issue by jypeter** [cf-convention/cf-convention.github.io#67]
I have just realized that there is no way to cite or even acknowledge the CF conventions. Or if there is, it is not easy to find it on the CF site.

Should there be some _zenodo stuff_ that can be cited (don't really know how this works), until the time there is a GMD (or other) paper about the CF conventions

And it would be useful to have a standard acknowledgment sentence that people can copy/paste, even if they usually forget about that...

**Comment by martinjuckes** [comment]
@jypeter : I agree, this would be a very useful step forward, and should not be difficult to implement.

One option would be to put the pdf document into Zenodo, with title and author information, which would then give it a clear standard format citation with a DOI.

Also (in parallel), it would make sense to have a recommended citation text at the front of the convention. In the days of print media that would lead into the idea of arranging the front of the convention in the pdf document somewhat more formally (e.g. front page with title etc, publication information on inside page, followed by  index, etc) -- I'm not sure what the equivalent structure is now that the focus is more on the on-line version.

**Comment by erget** [comment]
This looks stale - I'm closing it but please re-open if relevant!

Might be an interesting input for DOI discussions.

**Comment by matt-frey** [comment]
Hello, I am working on a project that tries to follow the CF convention. We are now writing a paper and want to cite the CF convention. We have not found a proper citation, but only this closed issue. How should we cite the CF convention? Many thanks.

**Comment by matt-frey** [comment]
Great, thanks! Best wishes, Matthias
