### ISSUE TITLE
Slight link error on home page

### ISSUE THREAD

**Issue by jypeter** [cf-convention/cf-convention.github.io#68]
When I hover over _take a look at the Discussion page_ on the home page, the displayed link is http://cf-convention.github.io/discussion.html when it should probably rather be http://cfconventions.org/discussion.html

**Comment by JonathanGregory** [comment]
Yes, I agree with you. We should change that. Thanks.

**Comment by JonathanGregory** [comment]
Please could someone check and merge https://github.com/cf-convention/cf-convention.github.io/pull/151 to correct an erroneous link on the CF home page. Any member of the committee or governance panel should be able to do this. Thanks.
