### ISSUE TITLE
udunits link on CF Standard Name Table page

### ISSUE THREAD

**Issue by zdefne-usgs** [cf-convention/cf-convention.github.io#69]
Link to **Udunits documentation** on the [CF Standard Name Table page](http://cfconventions.org/Data/cf-standard-names/63/build/cf-standard-name-table.html) is broken in all versions. It should be pointing to here (so that it will not break again when the Udunits version changes): 
https://www.unidata.ucar.edu/software/udunits/#documentation

or here for the current version:
https://www.unidata.ucar.edu/software/udunits/udunits-current/doc/udunits/udunits2.html

**Comment by japamment** [comment]
Thank you for raising this issue - all the links have now been fixed.
