### ISSUE TITLE
Rules for updating the CF data model

### ISSUE THREAD

**Issue by davidhassell** [cf-convention/cf-convention.github.io#71]
The CF data model will guide the development of CF by providing a framework for ensuring that proposed changes fit into CF in a logical way, rather than just a pragmatic one.

To ensure this occurs, some additional rules for conventions changes have been drafted in  Pull Request #72

In brief, a proposed change should be assessed for data model compatibility. If it is not compatible, and the proposal cannot be acceptably modified so that it is, then the data model will be changed to accommodate the change. The proposer is not required to have detailed data model knowledge - the new rules state that "The assessment will be carried out by a member of the conventions committee or another suitably qualified person. If no-one volunteers, the chairman of the committee will ask someone to do it".

See https://github.com/cf-convention/cf-conventions/issues/159 for more details.

**Comment by JonathanGregory** [comment]
I think this is fine, thanks, David. It would be useful if one or more other people could have a look at this proposed addition (to the rules for updating CF convention).

**Comment by erget** [comment]
Hi @davidhassell I've reviewed the PR and support these changes. I did include some non-blocking comments concerning the formulation of the text but not its contents.

**Comment by JonathanGregory** [comment]
My apologies. I merged https://github.com/cf-convention/cf-convention.github.io/pull/72 just now by mistake for https://github.com/cf-convention/cf-conventions/pull/250. However, @erget didn't intend his comment of 16 days ago cause a delay with this issue and @davidhassell has acted upon it, so there were no outstanding objections for three weeks and it had the required support according to the rules. Hence I hope it will be OK with everyone if we take this issue to be closed as well, and I will try to be more careful in future.
