### ISSUE TITLE
cf-metadata organization on github

### ISSUE THREAD

**Issue by graybeal** [cf-convention/cf-convention.github.io#8]
There is a cf-metadata organization on github: https://github.com/cf-metadata, with one repository in it called cf-conventions. The repository appears unmaintained (last update rhattersley March 10).

(Because this is the only repository that pluralizes convention in the name, it is more visible than the actual cf-convention repository for searches for 'cf conventions'.)

Can this repository be deleted, or else made fully active and up to date for its desired purpose?

**Comment by ethanrd** [comment]
All the repositories under the GitHub cf-metadata organization (https://github.com/cf-metadata) have been archived. However, there is still a version of the CF Conventions document (version 1.6) published on GitHub Pages (http://cf-metadata.github.io/) from the cf-metadata website repo (https://github.com/cf-metadata/cf-metadata.github.io). This should probably be turned off.

@rhattersley - Can you turn off the GitHub Pages for this repo?

**Comment by rhattersley** [comment]
Thanks for the notification, @ethanrd 👍

I created that organisation and its repositories during my conversion of the conventions from DocBook to AsciiDoc:
* https://github.com/cf-convention/cf-conventions/commit/eca16f4acf52490743c70aa2146a7d3580bb3580
* https://github.com/cf-convention/cf-conventions/pulls?q=is%3Apr+author%3Arhattersley+

How quickly the world moves on and one is forgotten. 😉 On the plus side, that just goes to show that the AsciiDoc version is now safely regarded as the definitive source and there is no longer a need for the old scripts and demos. I shall ditch the lot.

**Comment by JonathanGregory** [comment]
Googling "cf conventions" and "cf metadata" now gives me the CF home page https://cfconventions.org, and the next link is the wikipedia page about CF. The URLs mentioned above no longer exist. Richard @rhattersley has evidently removed them, as he said. Thanks for your valuable work on translating the conventions document to AsciiDoc, Richard. Your contribution will not be forgotten and nor will you. :smile:
