### ISSUE TITLE
Add CF constitution to the governance page

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#88]
In https://github.com/cf-convention/cf-convention.github.io/pull/87 I have made a modification to the governance page to create a link to the existing constitution from the white paper, which I converted to adoc. When this is merged, I will propose some small changes from the CF governance panel.

**Comment by davidhassell** [comment]
Thanks, Jonathan. 

I see that the PR comes with an error from the website build process, but I don't think that it's related to your new document (but I'm no expert!). 

I would be happy to merge the PR.

**Comment by JonathanGregory** [comment]
@ethanrd has merged it now, but the website build is still failing.

**Comment by ethanrd** [comment]
@JonathanGregory - The website is actually built automatically by GitHub Pages under the covers and appears to be working well. The PR related to this issue did get merged in and the change can be seen on the [governance page](http://cfconventions.org/governance.html) has a link to the [constitution](http://cfconventions.org/constitution.html).

The old Travis build does not do anything useful (it builds old DocBook versions) and is failing for reasons related to missing files that we no longer need. I have a PR (#93) that removes that Travis build but haven't merged that in yet, I'll merge that in later today. Another PR (#90) that set up a new build using GitHub Actions has been merged and appears to be working well.

**Comment by JonathanGregory** [comment]
So it is! Thanks, and well done. I was misled by the error messages. In that case I will now prepare modifications.

**Comment by ethanrd** [comment]
PR #87 has been merged which I believe should close this issue.

I will close but feel free to reopen if I'm wrong on this.

**Comment by ethanrd** [comment]
Closed by #87
