### ISSUE TITLE
Malformed date stamp for standard name table v23

### ISSUE THREAD

**Issue by sadielbartholomew** [cf-convention/cf-convention.github.io#89]
I have noticed, via an exception raised in a script I have wrote that parses the standard name tables across all versions including for the last modified dates, that there is a redundant colon in the ``last_modified`` date stamp for version 23 of the standard name table. For quick inspection, as copied from the head of the [relevant XML source file](https://github.com/cf-convention/cf-convention.github.io/blob/master/Data/cf-standard-names/23/src/cf-standard-name-table.xml):

```xml
<?xml version="1.0"?>
<standard_name_table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cf-standard-name-table-1.1.xsd">
   <version_number>23</version_number>
   <last_modified>2013-03-23:T12:30:00Z</last_modified>
```

Though this is an old version, ideally the misplaced colon could be removed for a correction, as the datetime as-is breaks ISO 8601 compliance & anyone who might want to parse the full dataset such as myself will have to add in lines to manually remove the colon before e.g. converting datetimes to other datetime formats such as Python ``datetime.datetime`` object.

**Comment by japamment** [comment]
Hi @sadielbartholomew many thanks for reporting this. The date stamp in V23 of the standard name table has now been fixed, so I'm closing this issue.

**Comment by sadielbartholomew** [comment]
Perfect, thank you for the quick fix.
