### ISSUE TITLE
changes to the CF constitution proposed by the governance panel

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#96]
In pull request https://github.com/cf-convention/cf-convention.github.io/pull/95 I have proposed minor changes that have been prepared by the CF governance panel to the constitution of CF. The panel is grateful to @erget for having prompted us to publish the constitution properly (rather than leaving it in an appendix to the white paper of 2006) and to consider how to bring it up to date.

The proposed changes are summarised below. Most of them write down the current practice, or delete transitional arrangements which are no longer relevant. We propose new arrangements to make the governance panel explicitly accountable to the WGCM, which is the guardian organisation of CF.

One provision that has not changed is that members of the committee have a term of five years, with possible reappointment. Although this has always been the rule it's never operated. Presuming we keep this provision, we should decide transitional arrangements for bringing it into operation, since most of the committee have already been members for more than five years. We can discuss that in a separate issue.

We don't have any rules for how to change the constitution, and we've never done it before, so I suggest that we apply the same three-week rule for comments as we do for changes to the convention.

I would request that any discussion about the wording of the changes should be done __here__ in the issue, and __not__ in the pull request, so that's all in one place. Thanks.

* Change the title from "Terms of reference", which is too narrow, to "Constitution".

* Insert an introductory paragraph of text from @erget about the intent of the governance arrangements and conduct of CF.

* Replace the statements about the inauguration of the governance panel by the WGCM with a paragraph about the present status of the panel with respect to the WGCM and how any concerns may be handled.

* State that the governance panel members and chair are chosen by the panel and have indefinite terms; this has always been the position but was not stated.

* Add to the terms of reference for the governance panel that it should promote the use of CF, ensure an annual meeting is organised, report annually to the WGCM, respond to any concerns about its own performance, and maintain a permanent public report of its deliberations.

* Remove the limits on numbers of members of the committees.

* Remove the statements about the inauguration of the committees.

* Remove paragraphs about the rules for deciding changes to the convention, because these are now contained in a separate document on the website.

* Add to the constitution of the committees that they should carry out their debates in public and maintain public records of their deliberations.

**Comment by erget** [comment]
Hi @JonathanGregory thanks for proposing and summarising these changes - I support this proposal.

**Comment by davidhassell** [comment]
Merged after the required three weeks have elapsed. Thanks.
