### ISSUE TITLE
update governance panel composition

### ISSUE THREAD

**Issue by JonathanGregory** [cf-convention/cf-convention.github.io#99]
https://github.com/cf-convention/cf-convention.github.io/pull/98 is a pull request to update the page listing committee membership, to show the new composition of the CF governance panel. After 20 years, Karl Taylor is retiring as chair of the governance panel but remaining a member of it. Rich Signell has decided to retire from the panel. Gratitude for their contributions to CF in these roles has been recorded on the web page. Daniel Lee has agreed to join the panel, representing the involvement of EUMETSAT in particular, and Ethan Davis has accepted the request of the other panel members to serve as its new chair. Thank you to them as well for taking on these new responsibilities.

I think this issue has the status of a defect, in that it intends to bring the web page up to date with reality. Please comment if you see any mistake in the pull request. Thanks.

**Comment by ethanrd** [comment]
Fixed by #98
